# BNP Paribas- Bussines Case Project 2025/2026
**DATA VISUALIZATION AND PREPROCESSING NOTEBOOK**

**Group V**:
   - Alano Gonçalves (20250457)
   - Catarina Martins (20221914)
   - João Carichas (20250507)
   - Marta Ribeiro (20221886)
   - Nicole Nogueira(20221961)

# Index

- [1. Import](#import)
  - [1.1 Import libraries](#import-libraries)
  - [1.2 Import the dataset](#import-the-dataset)
- [2. Data Exploration](#data-Exploration)
  - [2.1 MetaData](#metadata)
  - [2.2 Analysing the Data](#Analysing-the-Data)
  - [2.3 Data Visualization](#Data-visualization)
  - [2.4 Correlation Check](#correlation-check)
- [3. Data Quality & Feature Engineering](#Data-Quality-&-Feature-Engineering)
  - [3.1 Data Quality](#Data-Quality)
  - [3.2 Feature Engineering](#Feature-Engineering)
- [4. Implications for Clustering](#Implications-for-Clustering)

<div class="alert alert-block alert-info">

<a class="anchor" id="1. Import">    </a>
# 1. Import
       
</div>

[Back to Index](#index)

<a class="anchor" id="1.1 Import Libraries">

## 1.1 Import Libraries
    
</a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from math import ceil
from suport import *
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score   
from sklearn.impute import KNNImputer

<a class="anchor" id="1.2 Import the Dataset">

## 1.2 Import the Dataset
    
</a>

In [2]:
#pip install pandas pyarrow
#!pip install fastparquet

In [4]:
#Alano
file_path_CRC = r"C:\Users\alano\Desktop\Mestrado\2- Semestre\Busines case\BNP\Projeto GIt\crc.parquet"
file_path_CREDSCORE = r"C:\Users\alano\Desktop\Mestrado\2- Semestre\Busines case\BNP\Projeto GIt\BNP-Paribas\credscore.parquet"
file_path_BDOSS = r"C:\Users\alano\Desktop\Mestrado\2- Semestre\Busines case\BNP\Projeto GIt\bdoss.parquet"
file_path_FAMA = r"C:\Users\alano\Desktop\Mestrado\2- Semestre\Busines case\BNP\Projeto GIt\BNP-Paribas\fama.parquet"

# Ler o ficheiro parquet
CRC = pd.read_parquet(file_path_CRC, engine="fastparquet")
CREDSCORE = pd.read_parquet(file_path_CREDSCORE, engine="fastparquet")
FAMA = pd.read_parquet(file_path_FAMA, engine="fastparquet")
BDOSS = pd.read_parquet(file_path_BDOSS, engine="fastparquet")

In [ ]:
#joão
file_path_CRC = r"C:\Users\jcari\OneDrive\Ambiente de Trabalho\NOVA IMS\Business Cases\Case 1\crc.parquet"
file_path_CREDSCORE = r"C:\Users\jcari\OneDrive\Ambiente de Trabalho\BNP-Paribas-main\credscore.parquet"
file_path_BDOSS = r"C:\Users\jcari\OneDrive\Ambiente de Trabalho\NOVA IMS\Business Cases\Case 1\bdoss.parquet"
file_path_FAMA = r"C:\Users\jcari\OneDrive\Ambiente de Trabalho\BNP-Paribas-main\fama.parquet"

# Ler o ficheiro parquet
CRC = pd.read_parquet(file_path_CRC, engine="fastparquet")
CREDSCORE = pd.read_parquet(file_path_CREDSCORE, engine="fastparquet")
FAMA = pd.read_parquet(file_path_FAMA, engine="fastparquet")
BDOSS = pd.read_parquet(file_path_BDOSS, engine="fastparquet")

In [3]:
#marta
file_path_CRC = r"C:\Users\martr\OneDrive\Documentos\GitHub\crc.parquet"
file_path_CREDSCORE = r"C:\Users\martr\OneDrive\Documentos\GitHub\BNP-Paribas\credscore.parquet"
file_path_BDOSS = r"C:\Users\martr\OneDrive\Documentos\GitHub\BDOSS.parquet"
file_path_FAMA = r"C:\Users\martr\OneDrive\Documentos\GitHub\BNP-Paribas\fama.parquet"

# Ler o ficheiro parquet
CRC = pd.read_parquet(file_path_CRC, engine="fastparquet")
CREDSCORE = pd.read_parquet(file_path_CREDSCORE, engine="fastparquet")
FAMA = pd.read_parquet(file_path_FAMA, engine="fastparquet")
BDOSS = pd.read_parquet(file_path_BDOSS, engine="fastparquet")

<div class="alert alert-block alert-info">

<a class="anchor" id="2. Data Exploration">    </a>
# CRC Dataset
       
</div>

**METADATA:**
- *Date_Obs*: Observation Date (MMYY).
- *MT_MENSAL*: Sum of monthly installments paid by the client.
- *COUNT_CL*: Consumer credit count.
- *COUNT_CP*: Credit card or revolving credit count.
- *COUNT_AUTO*:  Auto loan credit count.
- *COUNT_HT*: Mortgage credit count.
- *COUNT_CONEXO*: Connected credit count.
- *COUNT_OTHER*: Other credits count.
- *COUNT_TOTAL*: Total credits count.
- *MONTVENC_CL*:  Sum of overdue amounts in consumer credit. 
- *MONTVENC_CP*:  Sum of overdue amounts in credit card and revolving credit.
- *MONTVENC_AUTO*:  Sum of overdue amounts in auto loans.
- *MONTVENC_HT*:  Sum of overdue amounts in mortgages.
- *MONTABATV_CL*:  Sum of written-off amounts in consumer credit.
- *MONTABATV_CP*:  Sum of written-off amounts in credit card and revolving credit.
- *MONTABATV_AUTO*:  Sum of written-off amounts in auto loans.
- *MONTABATV_HT*:  Sum of written-off amounts in mortgages.
- *DIVIDAS_CL*:   Total consumer credit debt.
- *DIVIDAS_CP*:  Total credit card and revolving credit debt.
- *DIVIDAS_AUTO*: Total auto loan debt.
- *DIVIDAS_HT*: Total mortgage debt.

<a class="anchor" id="2.2 Analysing the Data">

## 2. Analysing the Data
    
</a>

### 2.1. Data Overview

In [5]:
CRC.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3034921 entries, 0 to 3034920
Data columns (total 22 columns):
 #   Column          Dtype
---  ------          -----
 0   CONTRIB         object
 1   OBS_DATE        datetime64[ns]
 2   MT_MENSAL       float64
 3   COUNT_CL        float64
 4   COUNT_CP        float64
 5   COUNT_AUTO      float64
 6   COUNT_HT        float64
 7   COUNT_CONEXO    float64
 8   COUNT_OTHER     float64
 9   COUNT_TOTAL     float64
 10  MONTVENC_CL     float64
 11  MONTVENC_CP     float64
 12  MONTVENC_AUTO   float64
 13  MONTVENC_HT     float64
 14  MONTABATV_CL    float64
 15  MONTABATV_CP    float64
 16  MONTABATV_AUTO  float64
 17  MONTABATV_HT    float64
 18  DIVIDAS_CL      float64
 19  DIVIDAS_CP      float64
 20  DIVIDAS_AUTO    float64
 21  DIVIDAS_HT      float64
dtypes: datetime64[ns](1), float64(20), object(1)
memory usage: 509.4+ MB

- The most important (serious ones) are the MONTABATV. If those variables are too high, the client is not trustworthy.
- It is normal for a client to have DIVIDAS, but is preferable if they reduce month to month.

In [6]:
CRC.describe().round(2)

,OBS_DATE,MT_MENSAL,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,...,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
count,3034921,1029718.00,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00,...,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00,3034749.00
mean,2025-01-01 06:09:42.119141376,552.09,1.65,3.09,0.55,0.46,0.07,0.67,6.49,103.33,...,19.69,37.85,4.34,4.27,0.30,0.47,11438.98,2624.60,5403.67,30449.71
min,2023-12-31 00:00:00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
25%,2024-06-30 00:00:00,236.67,1.00,2.00,0.00,0.00,0.00,0.00,4.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,1128.30,132.84,0.00,0.00
50%,2024-12-31 00:00:00,446.60,1.00,3.00,0.00,0.00,0.00,0.00,6.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,6160.02,1133.66,0.00,0.00
75%,2025-06-30 00:00:00,724.99,2.00,4.00,1.00,1.00,0.00,1.00,8.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,15248.11,3219.76,8243.23,46515.51
max,2025-12-31 00:00:00,1224049.39,90.00,183.00,26.00,36.00,15.00,72.00,330.00,2923893.44,...,130756.11,807322.92,171424.67,62861.30,33127.84,288803.22,3194523.32,480181.93,514850.48,4582324.44
std,NaN,1736.58,1.65,2.41,0.76,0.73,0.30,0.88,4.07,2818.38,...,591.92,2541.25,285.17,209.89,59.54,211.27,17905.50,4414.23,9711.06,59607.22

In [7]:
CRC.tail()

,CONTRIB,OBS_DATE,MT_MENSAL,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,...,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
3034916,fffc5ec9541c7691c7759c637317530910cf44783e4209...,2025-12-31,NaN,3.0,4.0,1.0,1.0,0.0,2.0,11.0,...,0.0,0.0,0.0,0.0,0.0,0.0,11944.76,3285.33,2975.66,76534.61
3034917,fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc6...,2025-12-31,990.24,3.0,4.0,0.0,0.0,0.0,1.0,8.0,...,0.0,0.0,0.0,0.0,0.0,0.0,50534.29,1959.59,0.00,0.00
3034918,fffc991d73df732084dab58938d520b8a5d8712474fa53...,2025-12-31,NaN,0.0,2.0,0.0,0.0,0.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.00,0.00
3034919,fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a...,2025-12-31,NaN,1.0,1.0,1.0,0.0,0.0,0.0,3.0,...,0.0,0.0,0.0,0.0,0.0,0.0,2197.85,2213.10,18037.03,0.00
3034920,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-12-31,NaN,3.0,1.0,0.0,0.0,0.0,0.0,4.0,...,0.0,0.0,0.0,0.0,0.0,0.0,20193.99,3057.11,0.00,0.00

In [8]:
CRC = CRC.sort_values(['CONTRIB', 'OBS_DATE'])

In [9]:
#To each client, check the maximum and minimum number of each variable
CRC.groupby('CONTRIB').agg(['min', 'max'])

                                                     OBS_DATE             \
                                                          min        max
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f01... 2023-12-31 2025-12-31
0000ab2116257783438c70ff85a3e98f2d4194ebe534349... 2023-12-31 2025-12-31
0000f858346061c53064586a3347b34659565a6712d004e... 2023-12-31 2025-12-31
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c6... 2023-12-31 2025-12-31
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd... 2023-12-31 2025-11-30
...                                                       ...        ...
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67... 2023-12-31 2025-12-31
fffc991d73df732084dab58938d520b8a5d8712474fa539... 2023-12-31 2025-12-31
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9... 2023-12-31 2025-12-31
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c... 2023-12-31 2025-12-31
ffff943c736f98d4840f65328ba372a29689312dd781b43... 2023-12-31 2025-08-31

                                                   MT_MENSAL           \
                                                         min      max
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f01...       NaN      NaN
0000ab2116257783438c70ff85a3e98f2d4194ebe534349...    538.67   547.45
0000f858346061c53064586a3347b34659565a6712d004e...       NaN      NaN
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c6...    515.57   515.57
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd...       NaN      NaN
...                                                      ...      ...
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67...    305.96  1031.51
fffc991d73df732084dab58938d520b8a5d8712474fa539...       NaN      NaN
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9...       NaN      NaN
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c...       NaN      NaN
ffff943c736f98d4840f65328ba372a29689312dd781b43...       NaN      NaN

                                                   COUNT_CL       COUNT_CP  \
                                                        min   max      min
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f01...      0.0   1.0      3.0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349...      4.0  12.0      5.0
0000f858346061c53064586a3347b34659565a6712d004e...      1.0   2.0      5.0
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c6...      3.0   3.0      1.0
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd...      8.0  36.0      3.0
...                                                     ...   ...      ...
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67...      1.0   3.0      2.0
fffc991d73df732084dab58938d520b8a5d8712474fa539...      0.0   1.0      2.0
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9...      1.0   1.0      1.0
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c...      2.0   3.0      1.0
ffff943c736f98d4840f65328ba372a29689312dd781b43...      0.0   1.0      3.0

                                                         COUNT_AUTO       ...  \
                                                     max        min  max  ...
CONTRIB                                                                   ...
00008246f87bcc3c17b90629bb183fe2e58795176310f01...   9.0        0.0  6.0  ...
0000ab2116257783438c70ff85a3e98f2d4194ebe534349...  15.0        0.0  0.0  ...
0000f858346061c53064586a3347b34659565a6712d004e...  10.0        1.0  2.0  ...
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c6...   2.0        0.0  0.0  ...
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd...  16.0        0.0  0.0  ...
...                                                  ...        ...  ...  ...
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67...   8.0        0.0  1.0  ...
fffc991d73df732084dab58938d520b8a5d8712474fa539...   2.0        0.0  0.0  ...
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9...   1.0        1.0  1.0  ...
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c...   2.0        0.0  0.0  ...
ffff943c736f98d4840f65328ba372a29689312dd781b43...   5.0        1.0  1.0  ...

                                                   MONTABATV_HT       \
                                                            min  max
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f01...          0.0  0.0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349...          0.0  0.0
0000f858346061c53064586a3347b34659565a6712d004e...          0.0  0.0
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c6...          0.0  0.0
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd...          0.0  0.0
...                                                         ...  ...
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67...          0.0  0.0
fffc991d73df732084dab58938d520b8a5d8712474fa539...          0.0  0.0
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9...          0.0  0.0
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c...          0.0  0.0
ffff943c736f98d4840f65328ba372a29689312dd781b43...          0.0  0.0

                                                   DIVIDAS_CL             \
                                                          min        max
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f01...       0.00    8000.00
0000ab2116257783438c70ff85a3e98f2d4194ebe534349...   20308.94   69754.56
0000f858346061c53064586a3347b34659565a6712d004e...    1019.13    2957.28
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c6...   18566.68   27120.42
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd...   42783.96  204571.28
...                                                       ...        ...
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67...    3871.23  109094.96
fffc991d73df732084dab58938d520b8a5d8712474fa539...       0.00     460.38
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9...    2197.85    8758.64
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c...   13970.93   20351.05
ffff943c736f98d4840f65328ba372a29689312dd781b43...       0.00    2437.28

                                                   DIVIDAS_CP            \
                                                          min       max
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f01...       1.65   3701.73
0000ab2116257783438c70ff85a3e98f2d4194ebe534349...    5499.88  21274.83
0000f858346061c53064586a3347b34659565a6712d004e...    1465.73   3475.32
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c6...       0.00    362.05
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd...    4128.54  18144.16
...                                                       ...       ...
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67...       0.00   2488.34
fffc991d73df732084dab58938d520b8a5d8712474fa539...       0.00     29.97
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9...    1373.44   2382.31
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c...    2590.96   7224.97
ffff943c736f98d4840f65328ba372a29689312dd781b43...    1819.49   5024.58

                                                   DIVIDAS_AUTO            \
                                                            min       max
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f01...         0.00  58633.86
0000ab2116257783438c70ff85a3e98f2d4194ebe534349...         0.00      0.00
0000f858346061c53064586a3347b34659565a6712d004e...       773.46   2408.56
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c6...         0.00      0.00
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd...         0.00      0.00
...                                                         ...       ...
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67...         0.00   9158.02
fffc991d73df732084dab58938d520b8a5d8712474fa539...         0.00      0.00
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9...     18037.03  22856.02
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c...         0.00      0.00
ffff943c736f98d4840f65328ba372a29689312dd781b43...     18040.69  19534.81

                                                   DIVIDAS_HT
                                                          min        max
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f01...       0.00       0.00
0000ab2116257783438c70ff85a3e98f2d4194ebe534349...       0.00       0.00
0000f858346061c53064586a3347b34659565a6712d004e...   83852.71  168563.04
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c6...       0.00       0.00
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd...       0.00       0.00
...                                                       ...        ...
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67...       0.00       0.00
fffc991d73df732084dab58938d520b8a5d8712474fa539...       0.00       0.00
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9...       0.00       0.00
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c...       0.00       0.00
ffff943c736f98d4840f65328ba372a29689312dd781b43...       0.00       0.00

[141663 rows x 42 columns]

In [10]:
#how many months of data do we have per client
CRC['CONTRIB'].value_counts()

CONTRIB
000785e8aca11cecd0db680ef13a751aa97ccf322d033332c0a4aff8db6e868c    25
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c5ce4e07c92bfe1f3b    25
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981    25
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297    25
0000f858346061c53064586a3347b34659565a6712d004e64309c2473f76faed    25
                                                                    ..
9e8f09117f4ea75b219984761fbdf795ba8e49e669e3d8168f8130bd84bb1b08     1
9e997a7ba95af15492c406601b2973edadd506930affa825ea884cd8d066133a     1
9eaa8e8ad04d65875075ac51063d9e38f2d599fc08d8b6de1e9d802f28281549     1
9ea65350fcbfd95566703782a8e95043445e996aa9e550783c87c25c69d3ad14     1
76859523ebb3d71fa7a5aeb17a43970d0dde5a3800099131d24df5913bd660d3     1
Name: count, Length: 141663, dtype: int64

In [11]:
pd.set_option('display.max_columns', None)
CRC.sort_values(by=['CONTRIB','OBS_DATE'], ascending=False)
CRC.head(26)

,CONTRIB,OBS_DATE,MT_MENSAL,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,MONTVENC_CP,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
0,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2023-12-31,NaN,1.0,4.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6842.10,963.55,0.00,0.0
119091,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-01-31,NaN,1.0,4.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6782.21,2111.44,0.00,0.0
238477,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-02-29,NaN,1.0,4.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6721.85,312.81,0.00,0.0
357730,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-03-31,NaN,1.0,4.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6661.02,501.34,0.00,0.0
477210,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-04-30,NaN,1.0,4.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6599.72,997.36,0.00,0.0
597135,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-05-31,NaN,1.0,4.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6537.94,1067.19,0.00,0.0
717015,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-06-30,NaN,1.0,4.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8000.00,1729.30,0.00,0.0
837418,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-07-31,NaN,1.0,4.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8000.00,1729.30,0.00,0.0
957821,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-08-31,NaN,1.0,4.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8000.00,1729.30,0.00,0.0
1078224,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-09-30,NaN,0.0,4.0,1.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.65,16000.00,0.0
1199421,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-10-31,NaN,0.0,4.0,1.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.65,16000.00,0.0
1320618,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-11-30,NaN,0.0,4.0,1.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,267.68,15934.05,0.0
1442299,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-12-31,NaN,0.0,4.0,1.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,7.78,15867.39,0.0
1564572,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-01-31,NaN,0.0,4.0,1.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,288.06,15800.01,0.0
1686628,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-02-28,NaN,0.0,3.0,1.0,0.0,0.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,268.03,15731.91,0.0
1809010,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-03-31,NaN,0.0,3.0,2.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,252.31,19946.47,0.0
1931464,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-04-30,NaN,0.0,3.0,2.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,411.09,19847.51,0.0
2054049,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-05-31,NaN,0.0,3.0,2.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,814.71,19747.55,0.0
2176983,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-06-30,NaN,0.0,3.0,2.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,978.25,19646.59,0.0
2300220,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-07-31,NaN,0.0,9.0,6.0,0.0,0.0,3.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,3701.73,58633.86,0.0
2423700,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-08-31,NaN,0.0,3.0,2.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1930.37,19441.63,0.0
2546134,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-09-30,NaN,0.0,3.0,2.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,2231.87,19337.61,0.0
2669168,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-10-31,NaN,0.0,3.0,2.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,2223.08,19232.55,0.0
2791774,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-11-30,NaN,0.0,3.0,1.0,0.0,0.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,2156.79,23000.00,0.0
2913785,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2025-12-31,NaN,0.0,3.0,1.0,0.0,0.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,2088.17,22828.41,0.0
1,0000ab2116257783438c70ff85a3e98f2d4194ebe53434...,2023-12-31,547.18,4.0,5.0,0.0,0.0,0.0,1.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28532.06,7115.46,0.00,0.0

In [12]:
CRC['DIVIDAS_CL'].value_counts(dropna=False)

DIVIDAS_CL
0.00        567067
5000.00       4716
3000.00       2347
2500.00       2330
10000.00      2130
             ...
55710.24         1
55039.82         1
54367.68         1
53693.79         1
54388.12         1
Name: count, Length: 1463522, dtype: int64

### 2.2. Checking Duplicates

In [13]:
#checking number of duplicates
CRC.duplicated().sum()

np.int64(0)

### 2.3. Checking Missing Values

In [14]:
#checking number of missing values
CRC.isna().sum()

CONTRIB                 0
OBS_DATE                0
MT_MENSAL         2005203
COUNT_CL              172
COUNT_CP              172
COUNT_AUTO            172
COUNT_HT              172
COUNT_CONEXO          172
COUNT_OTHER           172
COUNT_TOTAL           172
MONTVENC_CL           172
MONTVENC_CP           172
MONTVENC_AUTO         172
MONTVENC_HT           172
MONTABATV_CL          172
MONTABATV_CP          172
MONTABATV_AUTO        172
MONTABATV_HT          172
DIVIDAS_CL            172
DIVIDAS_CP            172
DIVIDAS_AUTO          172
DIVIDAS_HT            172
dtype: int64

In [15]:
#checking umber of missing values in each column as a percentage
CRC.isna().sum()/len(CRC) * 100

CONTRIB            0.000000
OBS_DATE           0.000000
MT_MENSAL         66.071011
COUNT_CL           0.005667
COUNT_CP           0.005667
COUNT_AUTO         0.005667
COUNT_HT           0.005667
COUNT_CONEXO       0.005667
COUNT_OTHER        0.005667
COUNT_TOTAL        0.005667
MONTVENC_CL        0.005667
MONTVENC_CP        0.005667
MONTVENC_AUTO      0.005667
MONTVENC_HT        0.005667
MONTABATV_CL       0.005667
MONTABATV_CP       0.005667
MONTABATV_AUTO     0.005667
MONTABATV_HT       0.005667
DIVIDAS_CL         0.005667
DIVIDAS_CP         0.005667
DIVIDAS_AUTO       0.005667
DIVIDAS_HT         0.005667
dtype: float64

- MT_MENSAL tem bastantes missing values- provavelmente não é uma variavel que nos vá dar muita informação (mais de 66% é missing value)
- Todas as outras variaveis têm o mesmo numero de missing values que provavelmente pretence às mesmas linhas: pode ser removido

In [16]:
CRC[CRC['COUNT_CL'].isna()]

,CONTRIB,OBS_DATE,MT_MENSAL,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,MONTVENC_CP,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
120541,03371c474bc2eaf39d5a22222ca6b05a8751a77362b77f...,2024-01-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479523,04ef89de7d33bab517a2cbdf332dc6bb77f3b8e2561e42...,2024-04-30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719547,055f3f85601c087a8344d754fb336a273b02e7457bc4a1...,2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839950,055f3f85601c087a8344d754fb336a273b02e7457bc4a1...,2024-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
960353,055f3f85601c087a8344d754fb336a273b02e7457bc4a1...,2024-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236966,fcd94d024706a8660a0579a5bfdd1ee254de51123ce35c...,2024-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836676,fe7365ef0214334307216c6e886136af21c0cbba0ccd9e...,2024-06-30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
957079,fe7365ef0214334307216c6e886136af21c0cbba0ccd9e...,2024-07-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1077482,fe7365ef0214334307216c6e886136af21c0cbba0ccd9e...,2024-08-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1564348,ff8c78421817a783da1d5fe00c5880e3d654e54d6e119e...,2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
CRC[CRC['COUNT_CP'].isna()]

,CONTRIB,OBS_DATE,MT_MENSAL,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,MONTVENC_CP,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
120541,03371c474bc2eaf39d5a22222ca6b05a8751a77362b77f...,2024-01-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479523,04ef89de7d33bab517a2cbdf332dc6bb77f3b8e2561e42...,2024-04-30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719547,055f3f85601c087a8344d754fb336a273b02e7457bc4a1...,2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839950,055f3f85601c087a8344d754fb336a273b02e7457bc4a1...,2024-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
960353,055f3f85601c087a8344d754fb336a273b02e7457bc4a1...,2024-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236966,fcd94d024706a8660a0579a5bfdd1ee254de51123ce35c...,2024-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836676,fe7365ef0214334307216c6e886136af21c0cbba0ccd9e...,2024-06-30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
957079,fe7365ef0214334307216c6e886136af21c0cbba0ccd9e...,2024-07-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1077482,fe7365ef0214334307216c6e886136af21c0cbba0ccd9e...,2024-08-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1564348,ff8c78421817a783da1d5fe00c5880e3d654e54d6e119e...,2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
CRC[CRC['CONTRIB'] == 'c7e93bc661a9d5329ea48d365935197aecff39161303b6bf625189371f7ac23c']

,CONTRIB,OBS_DATE,MT_MENSAL,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,MONTVENC_CP,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
92851,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2023-12-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212165,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-01-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
331418,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-02-29,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
450836,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-03-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
570663,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-04-30,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
690551,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-05-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
810839,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-06-30,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
931242,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-07-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1051645,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-08-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1172696,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-09-30,431.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1293893,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-10-31,431.03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1415444,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-11-30,830.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1537588,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2024-12-31,829.55,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1659689,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-01-31,828.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1782010,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-02-28,397.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1904435,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-03-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2026982,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-04-30,396.89,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2149825,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-05-31,396.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2272999,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-06-30,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2396452,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-07-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2519133,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-08-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2642033,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-09-30,394.79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2764798,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-10-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2886934,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-11-30,394.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3008259,c7e93bc661a9d5329ea48d365935197aecff39161303b6...,2025-12-31,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

There are clients that do not have information about the all 25 months

### 2.4. Checking Outliers

In [19]:
metric_features= ['MT_MENSAL', 'COUNT_CL', 'COUNT_CP', 'COUNT_AUTO', 'COUNT_HT', 'COUNT_CONEXO', 'COUNT_OTHER', 'COUNT_TOTAL', 'MONTVENC_CL', 'MONTVENC_CP', 'MONTVENC_AUTO', 'MONTVENC_HT', 'MONTABATV_CL', 'MONTABATV_CP', 'MONTABATV_AUTO', 'MONTABATV_HT', 'DIVIDAS_CL', 'DIVIDAS_CP', 'DIVIDAS_AUTO', 'DIVIDAS_HT']

### 2.5. Checking Distribution

### 2.6. Checking Correlation between variables

### 2.7. Checking Incoherencies

In [20]:
CRC[CRC['COUNT_CL'] > CRC['DIVIDAS_CL']]

,CONTRIB,OBS_DATE,MT_MENSAL,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,MONTVENC_CP,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
2669300,004a4844d13c19d1ece1ba9d054f9f649722fc769d1b74...,2025-10-31,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
2791906,004a4844d13c19d1ece1ba9d054f9f649722fc769d1b74...,2025-11-30,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
2913915,004a4844d13c19d1ece1ba9d054f9f649722fc769d1b74...,2025-12-31,0.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
119230,004eb27ba7cf84b926c7fc7e61bfa841e1386f1704e440...,2024-01-31,0.0,1.0,3.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1585.08,0.0,0.0
238612,004eb27ba7cf84b926c7fc7e61bfa841e1386f1704e440...,2024-02-29,0.0,1.0,3.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1605.02,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1808962,ffeaef675c35b6708e168516178f2f503b4ee56f4499a9...,2025-02-28,NaN,1.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
1931416,ffeaef675c35b6708e168516178f2f503b4ee56f4499a9...,2025-03-31,NaN,1.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
2054001,ffeaef675c35b6708e168516178f2f503b4ee56f4499a9...,2025-04-30,NaN,1.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
2176935,ffeaef675c35b6708e168516178f2f503b4ee56f4499a9...,2025-05-31,NaN,1.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0
2300171,ffeaef675c35b6708e168516178f2f503b4ee56f4499a9...,2025-06-30,NaN,1.0,0.0,0.0,0.0,0.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0

In [21]:
CRC[CRC['COUNT_CP'] > CRC['DIVIDAS_CP']]

,CONTRIB,OBS_DATE,MT_MENSAL,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,MONTVENC_CP,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
1078224,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-09-30,NaN,0.0,4.0,1.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.65,16000.0,0.0
1199421,00008246f87bcc3c17b90629bb183fe2e58795176310f0...,2024-10-31,NaN,0.0,4.0,1.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,1.65,16000.0,0.0
2913788,00025459b703e1c308553e83a6d545a71fe6a787c2dd1c...,2025-12-31,515.57,3.0,2.0,0.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18566.68,0.00,0.0,0.0
1078230,00050fe9f0e69ce221a574af0baaff0b37c598af7a5cc6...,2024-09-30,113.79,1.0,2.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3153.88,0.00,0.0,0.0
1199427,00050fe9f0e69ce221a574af0baaff0b37c598af7a5cc6...,2024-10-31,113.79,1.0,2.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3153.88,0.00,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2546130,fffc991d73df732084dab58938d520b8a5d8712474fa53...,2025-08-31,NaN,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
2669165,fffc991d73df732084dab58938d520b8a5d8712474fa53...,2025-09-30,NaN,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
2791771,fffc991d73df732084dab58938d520b8a5d8712474fa53...,2025-10-31,NaN,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
2913782,fffc991d73df732084dab58938d520b8a5d8712474fa53...,2025-11-30,NaN,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0
3034918,fffc991d73df732084dab58938d520b8a5d8712474fa53...,2025-12-31,NaN,0.0,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.00,0.0,0.0

In [22]:
CRC[
    CRC['COUNT_CL'] +
    CRC['COUNT_CP'] +
    CRC['COUNT_AUTO'] +
    CRC['COUNT_HT'] +
    CRC['COUNT_CONEXO'] +
    CRC['COUNT_OTHER']
    != CRC['COUNT_TOTAL']
]

,CONTRIB,OBS_DATE,MT_MENSAL,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,MONTVENC_CP,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT
120541,03371c474bc2eaf39d5a22222ca6b05a8751a77362b77f...,2024-01-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
479523,04ef89de7d33bab517a2cbdf332dc6bb77f3b8e2561e42...,2024-04-30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719547,055f3f85601c087a8344d754fb336a273b02e7457bc4a1...,2024-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
839950,055f3f85601c087a8344d754fb336a273b02e7457bc4a1...,2024-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
960353,055f3f85601c087a8344d754fb336a273b02e7457bc4a1...,2024-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
236966,fcd94d024706a8660a0579a5bfdd1ee254de51123ce35c...,2024-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836676,fe7365ef0214334307216c6e886136af21c0cbba0ccd9e...,2024-06-30,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
957079,fe7365ef0214334307216c6e886136af21c0cbba0ccd9e...,2024-07-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1077482,fe7365ef0214334307216c6e886136af21c0cbba0ccd9e...,2024-08-31,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1564348,ff8c78421817a783da1d5fe00c5880e3d654e54d6e119e...,2024-12-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

<a class="anchor" id="2.2 Analysing the Data">

## 3. Data Preparation
    
</a>

### 3.1. Changing Datatypes

In [23]:
#CRC.set_index('CONTRIB', inplace = True)

In [24]:
#Changing Datatypes
CRC['COUNT_CL'] = CRC['COUNT_CL'].round().astype('Int32')
CRC['COUNT_CP'] = CRC['COUNT_CP'].round().astype('Int32')
CRC['COUNT_AUTO'] = CRC['COUNT_AUTO'].round().astype('Int32')
CRC['COUNT_HT'] = CRC['COUNT_HT'].round().astype('Int32')
CRC['COUNT_CONEXO'] = CRC['COUNT_CONEXO'].round().astype('Int32')
CRC['COUNT_OTHER'] = CRC['COUNT_OTHER'].round().astype('Int32')
CRC['COUNT_TOTAL'] = CRC['COUNT_TOTAL'].round().astype('Int32')

### 3.2. Handling Missing Values

In [25]:
#handling missing values of 172 rows
CRC = CRC.dropna(subset=['COUNT_CL'])

In [26]:
#droping MT_MENSAL due to its elevated number of missing values
CRC = CRC.drop(columns=['MT_MENSAL'])

In [27]:
#checking number of missing values
CRC.isna().sum()

CONTRIB           0
OBS_DATE          0
COUNT_CL          0
COUNT_CP          0
COUNT_AUTO        0
COUNT_HT          0
COUNT_CONEXO      0
COUNT_OTHER       0
COUNT_TOTAL       0
MONTVENC_CL       0
MONTVENC_CP       0
MONTVENC_AUTO     0
MONTVENC_HT       0
MONTABATV_CL      0
MONTABATV_CP      0
MONTABATV_AUTO    0
MONTABATV_HT      0
DIVIDAS_CL        0
DIVIDAS_CP        0
DIVIDAS_AUTO      0
DIVIDAS_HT        0
dtype: int64

### 3.3. Feature Engineering

In [28]:
CRC.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3034749 entries, 0 to 2546133
Data columns (total 21 columns):
 #   Column          Dtype
---  ------          -----
 0   CONTRIB         object
 1   OBS_DATE        datetime64[ns]
 2   COUNT_CL        Int32
 3   COUNT_CP        Int32
 4   COUNT_AUTO      Int32
 5   COUNT_HT        Int32
 6   COUNT_CONEXO    Int32
 7   COUNT_OTHER     Int32
 8   COUNT_TOTAL     Int32
 9   MONTVENC_CL     float64
 10  MONTVENC_CP     float64
 11  MONTVENC_AUTO   float64
 12  MONTVENC_HT     float64
 13  MONTABATV_CL    float64
 14  MONTABATV_CP    float64
 15  MONTABATV_AUTO  float64
 16  MONTABATV_HT    float64
 17  DIVIDAS_CL      float64
 18  DIVIDAS_CP      float64
 19  DIVIDAS_AUTO    float64
 20  DIVIDAS_HT      float64
dtypes: Int32(7), datetime64[ns](1), float64(12), object(1)
memory usage: 448.6+ MB

In [29]:
#creating 'MONTVENC_TOTAL'
CRC['MONTVENC_TOTAL'] = CRC[
    ['MONTVENC_CL','MONTVENC_CP','MONTVENC_AUTO','MONTVENC_HT']
].sum(axis=1)

In [30]:
#creating 'MONTABATV_TOTAL'
CRC['MONTABATV_TOTAL'] = CRC[
    ['MONTABATV_CL','MONTABATV_CP','MONTABATV_AUTO','MONTABATV_HT']
].sum(axis=1)

In [31]:
#has the client default history?
CRC['HIGH_RISK_CURRENT'] = (
    (CRC['MONTABATV_TOTAL'] > 0) | 
    (CRC['MONTVENC_TOTAL'] > 0)
).astype(int)

In [32]:
CRC['BALANCE_CL'] = (CRC['MONTVENC_CL'] - CRC['MONTABATV_CL'])
CRC['BALANCE_CP'] = (CRC['MONTVENC_CP'] - CRC['MONTABATV_CP'])
CRC['BALANCE_AUTO'] = (CRC['MONTVENC_AUTO'] - CRC['MONTABATV_AUTO'])
CRC['BALANCE_HT'] = (CRC['MONTVENC_HT'] - CRC['MONTABATV_HT'])

cols_to_move = ['BALANCE_CL', 'BALANCE_CP', 'BALANCE_AUTO', 'BALANCE_HT']

for col in reversed(cols_to_move):
    col_data = CRC.pop(col)
    CRC.insert(10, col, col_data)

In [33]:
#CRC = CRC.drop(columns=['MONTVENC_CL', 'MONTABATV_CL', 'MONTVENC_CP', 'MONTABATV_CP', 'MONTVENC_AUTO', 'MONTABATV_AUTO', 'MONTVENC_HT', 'MONTABATV_HT', 'MONTVENC_TOTAL', 'MONTABATV_TOTAL'])

In [34]:
pd.set_option('display.max_columns', None)
CRC = CRC.sort_values(['CONTRIB', 'OBS_DATE'])
CRC.tail(30)

,CONTRIB,OBS_DATE,COUNT_CL,COUNT_CP,COUNT_AUTO,COUNT_HT,COUNT_CONEXO,COUNT_OTHER,COUNT_TOTAL,MONTVENC_CL,BALANCE_CL,BALANCE_CP,BALANCE_AUTO,BALANCE_HT,MONTVENC_CP,MONTVENC_AUTO,MONTVENC_HT,MONTABATV_CL,MONTABATV_CP,MONTABATV_AUTO,MONTABATV_HT,DIVIDAS_CL,DIVIDAS_CP,DIVIDAS_AUTO,DIVIDAS_HT,MONTVENC_TOTAL,MONTABATV_TOTAL,HIGH_RISK_CURRENT
717013,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-05-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17345.04,3320.12,0.00,0.0,0.00,0.0,0
837416,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-06-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17512.16,3244.15,0.00,0.0,0.00,0.0,0
957819,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-07-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17512.16,3244.15,0.00,0.0,0.00,0.0,0
1078222,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-08-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17512.16,3244.15,0.00,0.0,0.00,0.0,0
1199420,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-09-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17218.32,3011.78,0.00,0.0,0.00,0.0,0
1320617,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-10-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17218.32,3011.78,0.00,0.0,0.00,0.0,0
1442298,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-11-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17143.40,3272.10,0.00,0.0,0.00,0.0,0
1564571,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2024-12-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,17067.34,3158.29,0.00,0.0,0.00,0.0,0
1686627,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-01-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16991.81,2885.36,0.00,0.0,0.00,0.0,0
1809009,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-02-28,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16914.79,2949.03,0.00,0.0,0.00,0.0,0
1931463,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-03-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16838.63,2990.12,0.00,0.0,0.00,0.0,0
2054048,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-04-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16759.90,2757.52,0.00,0.0,0.00,0.0,0
2176982,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-05-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16682.17,2712.68,0.00,0.0,0.00,0.0,0
2300219,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-06-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16602.33,2590.96,0.00,0.0,0.00,0.0,0
2423699,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-07-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16522.47,2666.02,0.00,0.0,0.00,0.0,0
2546132,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-08-31,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16442.01,2689.23,0.00,0.0,0.00,0.0,0
2669167,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-09-30,2,1,0,0,0,0,3,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,16361.05,2890.43,0.00,0.0,0.00,0.0,0
2791773,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-10-31,3,1,0,0,0,0,4,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,20351.05,2990.38,0.00,0.0,0.00,0.0,0
2913784,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-11-30,3,1,0,0,0,0,4,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,20319.04,3144.85,0.00,0.0,0.00,0.0,0
3034920,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00...,2025-12-31,3,1,0,0,0,0,4,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,20193.99,3057.11,0.00,0.0,0.00,0.0,0
119090,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2023-12-31,1,3,1,0,0,0,5,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,2272.16,2088.13,18144.16,0.0,0.00,0.0,0
238476,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-01-31,1,3,1,0,0,0,5,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.0,0.0,0.0,0.0,2291.34,2439.24,18144.16,0.0,0.00,0.0,0
357729,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-02-29,1,5,1,0,0,0,7,116.84,116.84,75.84,0.00,0.0,75.84,0.00,0.0,0.0,0.0,0.0,0.0,2322.45,2512.05,18040.69,0.0,192.68,0.0,1
477209,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-03-31,1,5,1,0,0,0,7,234.93,234.93,154.73,104.30,0.0,154.73,104.30,0.0,0.0,0.0,0.0,0.0,2341.30,4605.99,18555.47,0.0,493.96,0.0,1
597134,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-04-30,1,5,1,0,0,0,7,366.40,366.40,321.63,209.43,0.0,321.63,209.43,0.0,0.0,0.0,0.0,0.0,2372.98,4733.47,18830.21,0.0,897.46,0.0,1
717014,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-05-31,1,5,1,0,0,0,7,498.70,498.70,480.97,315.41,0.0,480.97,315.41,0.0,0.0,0.0,0.0,0.0,2404.92,4827.76,19103.31,0.0,1295.08,0.0,1
837417,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-06-30,1,4,1,0,0,0,6,2437.28,2437.28,748.84,422.23,0.0,748.84,422.23,0.0,0.0,0.0,0.0,0.0,2437.28,5024.58,18581.09,0.0,3608.35,0.0,1
957820,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-07-31,1,4,1,0,0,0,6,2437.28,2437.28,748.84,422.23,0.0,748.84,422.23,0.0,0.0,0.0,0.0,0.0,2437.28,5024.58,18581.09,0.0,3608.35,0.0,1
1078223,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2024-08-31,1,4,1,0,0,0,6,2437.28,2437.28,748.84,422.23,0.0,748.84,422.23,0.0,0.0,0.0,0.0,0.0,2437.28,5024.58,18581.09,0.0,3608.35,0.0,1
2546133,ffff943c736f98d4840f65328ba372a29689312dd781b4...,2025-08-31,0,3,1,0,0,0,4,0.00,0.00,1812.86,18040.69,0.0,1812.86,18040.69,0.0,0.0,0.0,0.0,0.0,0.00,1819.49,19534.81,0.0,19853.55,0.0,1

In [35]:
def moda(series):
    m = series.mode()
    return m.iloc[0] if not m.empty else np.nan

### 3.4. Aggregation

In [36]:
#aggregating CRC's variables 
CRC_agg = (
    CRC
    .groupby("CONTRIB", as_index=True)
    .agg(
        count_cl_mean=("COUNT_CL", "mean"),
        count_cl_mode=("COUNT_CL", moda),
        count_cp_mean=("COUNT_CP", "mean"),
        count_cp_mode=("COUNT_CP", moda),
        count_auto_mean=("COUNT_AUTO", "mean"),
        count_auto_mode=("COUNT_AUTO", moda),
        count_ht_mean=("COUNT_HT", "mean"),
        count_ht_mode=("COUNT_HT", moda),
        count_conexo_mean=("COUNT_CONEXO", "mean"),
        count_conexo_mode=("COUNT_CONEXO", moda),
        count_other_mean=("COUNT_OTHER", "mean"),
        count_other_mode=("COUNT_OTHER", moda),
        montvenc_cl_mean= ("MONTVENC_CL", "mean"),
        montvenc_cl_mode= ("MONTVENC_CL", moda),
        montvenc_cp_mean= ("MONTVENC_CP", "mean"),
        montvenc_cp_mode= ("MONTVENC_CP", moda),
        montvenc_auto_mean= ("MONTVENC_AUTO", "mean"),
        montvenc_auto_mode= ("MONTVENC_AUTO", moda),
        montvenc_ht_mean= ("MONTVENC_HT", "mean"),
        montvenc_ht_mode= ("MONTVENC_HT", moda),
        montabatv_cl_mean= ("MONTABATV_CL", "mean"),
        montabatv_cl_mode= ("MONTABATV_CL", moda),
        montabatv_cp_mean= ("MONTABATV_CP", "mean"),
        montabatv_cp_mode= ("MONTABATV_CL", moda),
        montabatv_auto_mean= ("MONTABATV_AUTO", "mean"),
        montabatv_auto_mode= ("MONTABATV_AUTO", moda),
        montabatv_ht_mean= ("MONTABATV_HT", "mean"),
        montabatv_ht_mode= ("MONTABATV_HT", moda),
        balance_cl_mean=("BALANCE_CL", "mean"),
        balance_cl_mode=("BALANCE_CL", moda),
        balance_cp_mean=("BALANCE_CP", "mean"),
        balance_cp_mode=("BALANCE_CP", moda),
        balance_auto_mean=("BALANCE_AUTO", "mean"),
        balance_auto_mode=("BALANCE_AUTO", moda),
        balance_ht_mean=("BALANCE_HT", "mean"),
        balance_ht_mode=("BALANCE_HT", moda),
        dividas_cl_mean=("DIVIDAS_CL", "mean"),
        dividas_cl_mode=("DIVIDAS_CL", moda),
        dividas_cp_mean=("DIVIDAS_CP", "mean"),
        dividas_cp_mode=("DIVIDAS_CP", moda),
        dividas_auto_mean=("DIVIDAS_AUTO", "mean"),
        dividas_auto_mode=("DIVIDAS_AUTO", moda),
        dividas_ht_mean=("DIVIDAS_HT", "mean"),
        dividas_ht_mode=("DIVIDAS_HT", moda),
    )
)

In [37]:
CRC_agg.head()

,count_cl_mean,count_cl_mode,count_cp_mean,count_cp_mode,count_auto_mean,count_auto_mode,count_ht_mean,count_ht_mode,count_conexo_mean,count_conexo_mode,count_other_mean,count_other_mode,montvenc_cl_mean,montvenc_cl_mode,montvenc_cp_mean,montvenc_cp_mode,montvenc_auto_mean,montvenc_auto_mode,montvenc_ht_mean,montvenc_ht_mode,montabatv_cl_mean,montabatv_cl_mode,montabatv_cp_mean,montabatv_cp_mode,montabatv_auto_mean,montabatv_auto_mode,montabatv_ht_mean,montabatv_ht_mode,balance_cl_mean,balance_cl_mode,balance_cp_mean,balance_cp_mode,balance_auto_mean,balance_auto_mode,balance_ht_mean,balance_ht_mode,dividas_cl_mean,dividas_cl_mode,dividas_cp_mean,dividas_cp_mode,dividas_auto_mean,dividas_auto_mode,dividas_ht_mean,dividas_ht_mode
CONTRIB,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,0.36,0,3.8,4,1.12,0,0.0,0,0.0,0,1.08,1,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,2565.793600,0.00,1150.592400,1729.30,13479.8216,0.00,0.0000,0.00
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,4.32,4,5.4,5,0.0,0,0.0,0,0.0,0,1.08,1,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,26448.032000,26637.90,7552.117200,6746.45,0.0000,0.00,0.0000,0.00
0000f858346061c53064586a3347b34659565a6712d004e64309c2473f76faed,1.04,1,5.2,5,1.04,1,1.04,1,0.0,0,0.0,0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,2082.786000,2508.37,1854.039600,1732.58,1665.2756,2026.99,88154.7832,85212.87
00025459b703e1c308553e83a6d545a71fe6a787c2dd1c62d26faa0207cc5b08,3.0,3,1.28,1,0.0,0,0.0,0,0.0,0,1.0,1,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,22980.086400,25108.29,102.284800,18.00,0.0000,0.00,0.0000,0.00
00041ebafb1270a818c30cb1fb20d3699002196644ea8fd9df9425df6f49db00,9.75,9,3.875,3,0.0,0,0.0,0,0.0,0,1.625,1,2416.34125,0.0,1622.499583,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2416.34125,0.0,1622.499583,0.0,0.0,0.0,0.0,0.0,55289.663333,42783.96,4865.075417,4181.68,0.0000,0.00,0.0000,0.00

<div class="alert alert-block alert-info">

<a class="anchor" id="2. Data Exploration">    </a>
# CREDSCORE Dataset
       
</div>

**METADATA**:
- *sys_numero_submissao*: Submission number. 
- *sys_data_procura*: Date of risk probing.
- *kp_sqe*: Risk score of known customers based on behavior: A-X, A is better, null= unknown.
- *ks_score_tier*: risk score for granting (all customers) lower is better.

<a class="anchor" id="2.2 Analysing the Data">

## 2. Analysing the Data
    
</a>

### 2.1. Data Overview

In [38]:
CREDSCORE.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 63704 entries, 0 to 63703
Data columns (total 5 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   CONTRIB               63704 non-null  object
 1   sys_numero_submissao  63704 non-null  float64
 2   sys_data_procura      63704 non-null  datetime64[ns]
 3   kp_sqe                45653 non-null  object
 4   ks_score_tier         63704 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(2)
memory usage: 2.4+ MB

In [39]:
CREDSCORE.describe().round(2)

       sys_numero_submissao               sys_data_procura  ks_score_tier
count              63704.00                          63704       63704.00
mean                   5.86  2024-08-26 19:30:49.503955968           1.59
min                    0.00            2020-08-12 00:00:00           1.00
25%                    3.00            2023-12-07 00:00:00           1.00
50%                    5.00            2024-10-10 00:00:00           1.00
75%                    8.00            2025-06-05 00:00:00           2.00
max                   62.00            2025-12-15 00:00:00           5.00
std                    4.19                            NaN           0.84

In [40]:
#descriptive statistics for categorical data
CREDSCORE.describe(include = ['O'])

                                                  CONTRIB kp_sqe
count                                               63704  45653
unique                                              62173     15
top     0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9...      A
freq                                                   20   6977

In [41]:
#how many clients exists for each classification (Alphabetical order)
CREDSCORE['kp_sqe'] \
    .value_counts(dropna=False) \
    .sort_index()

kp_sqe
A        6977
B        5404
C        4205
D        4638
E        6300
F        6085
G        3386
H        4788
I        1476
J         665
K         499
M         155
U         600
V         128
W         347
None    18051
Name: count, dtype: int64

- We can see the most common classification is 'A' which is a good indicator, and there is no client with classification 'X' (the worst)
- We should see what classification is considered risky

In [42]:
CREDSCORE['ks_score_tier'].value_counts(dropna=False)

ks_score_tier
1.0    39117
2.0    12670
3.0    10961
4.0      633
5.0      323
Name: count, dtype: int64

- The most common one is 1, which is also a good indicator.

### 2.2. Checking Duplicates

In [43]:
#checking number of duplicates
CREDSCORE.duplicated().sum()

np.int64(831)

In [44]:
dups = CREDSCORE[CREDSCORE.duplicated(subset=["CONTRIB"], keep=False)].sort_values("CONTRIB")
display(dups.head(20))

,CONTRIB,sys_numero_submissao,sys_data_procura,kp_sqe,ks_score_tier
47,0026b5f0de9828ec21d97c586dc791fb0671a0224617d1...,1.0,2024-03-20,H,2.0
48,0026b5f0de9828ec21d97c586dc791fb0671a0224617d1...,1.0,2024-03-20,H,1.0
202,00c37349b39ab60123c5f27d2a6dbed7491c55650506d6...,1.0,2023-09-12,D,3.0
203,00c37349b39ab60123c5f27d2a6dbed7491c55650506d6...,1.0,2023-09-12,D,2.0
249,00f7e9f67656f7f492faef74c1452f49148c0969f54e35...,1.0,2023-06-15,U,3.0
250,00f7e9f67656f7f492faef74c1452f49148c0969f54e35...,1.0,2023-06-15,U,3.0
263,01075c43c0ff8ec7ff76ffe65db4231a528099497f5d7d...,1.0,2025-08-19,None,5.0
264,01075c43c0ff8ec7ff76ffe65db4231a528099497f5d7d...,1.0,2025-08-19,None,2.0
341,01528f21434f34c7976541dca95691cea0b4778577c537...,1.0,2024-07-04,None,4.0
342,01528f21434f34c7976541dca95691cea0b4778577c537...,1.0,2024-07-04,None,2.0
357,016998a906ca0c00114c86ae62bebb98d6d55d7d3d5efc...,1.0,2025-12-10,U,3.0
358,016998a906ca0c00114c86ae62bebb98d6d55d7d3d5efc...,1.0,2025-12-10,U,2.0
371,0177cc8863841377a2e828078db37e3ef370e41c07a747...,1.0,2025-11-20,None,5.0
372,0177cc8863841377a2e828078db37e3ef370e41c07a747...,1.0,2025-11-20,None,5.0
477,01e0595798611e71b834ce47ea929ee24ff14aa3d97d9b...,1.0,2023-03-08,F,1.0
476,01e0595798611e71b834ce47ea929ee24ff14aa3d97d9b...,1.0,2023-03-08,F,3.0
536,022afaa0b0224ecea1e992cbd15397538727c8fe23ab0c...,1.0,2023-04-28,J,4.0
537,022afaa0b0224ecea1e992cbd15397538727c8fe23ab0c...,1.0,2023-04-28,J,2.0
547,02362a85557134b3c9c2bccb51c9722f13e3129286fb84...,1.0,2023-03-27,G,3.0
548,02362a85557134b3c9c2bccb51c9722f13e3129286fb84...,1.0,2023-03-27,G,1.0

In [45]:
CREDSCORE = CREDSCORE.sort_values(['CONTRIB'])

In [46]:
# Show all columns
pd.set_option('display.max_columns', None)

# Show full content of each column (no truncation)
pd.set_option('display.max_colwidth', None)

# Optional: increase display width for better readability
pd.set_option('display.width', 200)

# Display the first 10 duplicated rows sorted by 'CONTRIB'
duplicated_rows = CREDSCORE[CREDSCORE.duplicated()]
duplicated_rows.sort_values(['CONTRIB']).head(10)

                                                               CONTRIB  sys_numero_submissao sys_data_procura kp_sqe  ks_score_tier
250   00f7e9f67656f7f492faef74c1452f49148c0969f54e3522c3ff7ea0e9fa5e56                   1.0       2023-06-15      U            3.0
371   0177cc8863841377a2e828078db37e3ef370e41c07a74754f76bccce11470b1e                   1.0       2025-11-20   None            5.0
795   0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-03-23      H            2.0
1036  0409d4ca80af441a716c8306061d0e3b1b93bd75143c3c9b1d9f360d8488c368                   0.0       2024-07-17      G            2.0
1105  044f2375bbefdd1d9f5bca900e22eca71f7a87e0a06cf214c78d1efa02513086                   0.0       2023-09-06      E            1.0
1139  0472bdf64157b19fa8fd7bd32d3cd0a7c0de3d1490e857677fa1d30516f206cb                   1.0       2025-03-11      C            1.0
1169  048dcfd5d00fc43a1b8c23283cbd8ff885013f437451214eb5fe93e458ca7ec5                   1.0       2025-12-10      I            2.0
1203  04af1626e026f1237ed33a6e9904c44f9748ee04c58a5d4ca057bd1b3a9ff695                   1.0       2025-05-26      E            3.0
1229  04cd1bc1a93cad7b0d1cd894f6fcad04f970491ba0f64013c52f1563189f1eca                   1.0       2024-12-26      G            2.0
1247  04e6b3fd5cd02bfdd96f6d85f5f85decdd259a5b969f24a2646e9075e75493f9                   0.0       2023-09-26      U            1.0

### 2.3. Checking Incoherencies

In [47]:
print("shape:", CREDSCORE.shape)
print("clientes únicos:", CREDSCORE['CONTRIB'].nunique())
print("duplicados por cliente:", CREDSCORE.duplicated(subset=['CONTRIB']).sum())

shape: (63704, 5)
clientes únicos: 62173
duplicados por cliente: 1531

- There are 700 duplicates in *CONTRIB*

In [48]:
CREDSCORE['sys_data_procura'] = pd.to_datetime(CREDSCORE['sys_data_procura'], errors='coerce')

# número de datas diferentes por cliente
dates_per_client = CREDSCORE.groupby('CONTRIB')['sys_data_procura'].nunique()

print("Clients with >1 date:", (dates_per_client > 1).sum())

Clients with >1 date: 106

- There are 106 clients that have more than 1 date, which is not possible because in this dataset we are only considering the date of client's last credit proposal.

In [49]:
CREDSCORE[CREDSCORE['CONTRIB']=='0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557']

                                                              CONTRIB  sys_numero_submissao sys_data_procura kp_sqe  ks_score_tier
811  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2025-05-20   None            5.0
810  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2025-02-05   None            5.0
809  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2024-07-26   None            5.0
808  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2024-07-23   None            5.0
806  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2024-05-23   None            5.0
805  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2024-05-15   None            5.0
804  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2024-05-07   None            5.0
803  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2024-04-02   None            5.0
802  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2024-02-14   None            5.0
807  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2024-05-27   None            5.0
800  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-11-07   None            5.0
799  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-07-13   None            3.0
798  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-06-13   None            3.0
797  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-04-20      H            2.0
796  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-03-23      H            2.0
801  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2024-01-25   None            5.0
795  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-03-23      H            2.0
794  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-03-20      H            1.0
793  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-02-20      H            1.0
792  0327b5a9a23ce7ae7b9256d3d823ad083b8f499400d8b9fcc73203df81780557                   0.0       2023-02-01      H            1.0

### 2.4. Checking Missing Values

In [50]:
CREDSCORE['kp_sqe'] = CREDSCORE['kp_sqe'].astype(str).str.strip().str.upper()
CREDSCORE['kp_sqe'] = CREDSCORE['kp_sqe'].replace({'NULL': np.nan, 'NONE': np.nan})

In [51]:
#checking umber of missing values in each column as a percentage
CREDSCORE.isna().sum()/len(CREDSCORE) * 100

CONTRIB                  0.00000
sys_numero_submissao     0.00000
sys_data_procura         0.00000
kp_sqe                  28.33574
ks_score_tier            0.00000
dtype: float64

In [52]:
#checking number of missing values
CREDSCORE.isna().sum()

CONTRIB                     0
sys_numero_submissao        0
sys_data_procura            0
kp_sqe                  18051
ks_score_tier               0
dtype: int64

- This missing values correspond to unknown clients.

### 2.5. Checking Outliers

In [53]:
metric_features= ['ks_score_tier']

### 2.6. Checking Distribution

#### 2.6.1. Numerical Variable

In [54]:
df= pd.DataFrame(CREDSCORE[metric_features])

#### 2.6.2. Categorical Variable

<a class="anchor" id="2.2 Analysing the Data">

## 3. Data Preparation
    
</a>

### 3.1. Handling Incoherencies

In [55]:
# remover colunas técnicas
CREDSCORE = CREDSCORE.drop(columns=['sys_numero_submissao','sys_hora_procura'], errors='ignore')

In [56]:
CREDSCORE = CREDSCORE.sort_values(['CONTRIB','sys_data_procura'])
CREDSCORE = CREDSCORE.groupby('CONTRIB', as_index=False).tail(1)

In [57]:
print("shape:", CREDSCORE.shape)
print("clientes únicos:", CREDSCORE['CONTRIB'].nunique())
print("duplicados por cliente:", CREDSCORE.duplicated(subset=['CONTRIB']).sum())

shape: (62173, 4)
clientes únicos: 62173
duplicados por cliente: 0

ficamos apenas com a última linha de cada cliente
a variável 'kp_sqe' tem

In [58]:
CREDSCORE.groupby(CREDSCORE['kp_sqe'].isna())['ks_score_tier'].describe()

          count      mean       std  min  25%  50%  75%  max
kp_sqe
False   44389.0  1.463944  0.738791  1.0  1.0  1.0  2.0  5.0
True    17784.0  1.844861  0.941910  1.0  1.0  2.0  3.0  5.0

Para analisar o 'ks_score_tier' dos valores com e sem 'kp_sqe' (true é com missing value)

Em média os clientes com missing values têm média do score mais alto, ou seja risco mais elevado (como a empresa tem menos confiança neles assume maior incerteza e score pior, faz sentido)

### 3.2. Removing Duplicates

In [59]:
#droping duplicate rows 
CREDSCORE = CREDSCORE.drop_duplicates()

In [60]:
for col in CREDSCORE.columns:
    print(f"'{col}'")

'CONTRIB'
'sys_data_procura'
'kp_sqe'
'ks_score_tier'

In [61]:
CREDSCORE['sys_data_procura'] = pd.to_datetime(CREDSCORE['sys_data_procura'])

CREDSCORE = CREDSCORE.loc[
    CREDSCORE.groupby('CONTRIB')['sys_data_procura'].idxmax()
]

print(CREDSCORE)

                                                                CONTRIB sys_data_procura kp_sqe  ks_score_tier
0      00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981       2025-02-05      H            2.0
1      0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297       2025-04-09      D            1.0
2      00041ebafb1270a818c30cb1fb20d3699002196644ea8fd9df9425df6f49db00       2023-08-08      F            3.0
3      00050fe9f0e69ce221a574af0baaff0b37c598af7a5cc6eb42a2afd52d4e0d4a       2023-09-11      A            1.0
4      0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5       2025-08-14      H            1.0
...                                                                 ...              ...    ...            ...
63698  fff9d6d8fa1e236901f5dfd67c755b924aa7fa975250114d4aab9b1f09f9236a       2025-06-16      B            1.0
63699  fffa36f944396a3e75f9c54900165502a3eb725962144bd97f6af33e8ba6fac2       2023-08-04      E            1.0
63700  fffa9ff4598e3f04fa8eef5903352d5130126481085b1868266697a619e368e7       2025-01-22      G            2.0
63702  fffbc66ca4256976c9932916770f1ff3b23aacce5998ffc7d570a73378d619df       2025-05-31      H            1.0
63703  fffbfb06fdb05fb48a739b0a23650122a66ff61669a5b3e34d22144d0f0c2049       2025-03-03      C            1.0

[62173 rows x 4 columns]

### 3.3. Handling Missing Values

In [62]:
#filling missing values
CREDSCORE['kp_sqe'] = CREDSCORE['kp_sqe'].fillna('NO_BEHAVIOR_HISTORY')

### 3.4. Feature Engineering

In [63]:
#creating is_risky 
CREDSCORE['is_risky'] = (
    (CREDSCORE['kp_sqe'] > 'D') |
    (CREDSCORE['ks_score_tier'] > 2)
)

In [64]:
CREDSCORE['is_risky'].value_counts(dropna=False)

is_risky
True     42302
False    19871
Name: count, dtype: int64

In [65]:
CREDSCORE.head()

                                                            CONTRIB sys_data_procura kp_sqe  ks_score_tier  is_risky
0  00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981       2025-02-05      H            2.0      True
1  0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297       2025-04-09      D            1.0     False
2  00041ebafb1270a818c30cb1fb20d3699002196644ea8fd9df9425df6f49db00       2023-08-08      F            3.0      True
3  00050fe9f0e69ce221a574af0baaff0b37c598af7a5cc6eb42a2afd52d4e0d4a       2023-09-11      A            1.0     False
4  0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5       2025-08-14      H            1.0      True

<div class="alert alert-block alert-info">

<a class="anchor" id="2. Data Exploration">    </a>
# FAMA Dataset
       
</div>

**METADATA**
- *Date_Obs*: Observation Date (MMYY).
- *ALLBD_N_Dossiers__N*: Distinct count of Dossiers.
- *ALLBD_N_CL__N*: Distinct count of Dossiers for CL.
- *ALLBD_N_CP__N*: Distinct count of Dossiers for CP.
- *ALLBD_A_CL__N*: Distinct count of Dossiers for active CL.
- *ALLBD_A_CP__N*: Distinct count of Dossiers for active CP.
- *ALLBD_MTFINO_CL__N*: Number financings on CL - Total ammount.
- *ALLBD_MTFINO_CP__N*: Number financings on CP -Total ammount.
- *ALLBD_MTFIN_CL__N*: Presently financed on CL -present.
- *ALLBD_MTFIN_CP__N*: presently financed on CP -present.
- *ALLBD_IDADE_MSA__N*: max antiquity of contracts.
- *ALLBD_IDADE_MIN__N*: min antiquity of contracts.
- *ALLBD_IDADE_MEAN__N*: mean antiquity of contracts.
- *ALLBD_SUM_NUMFIN_CP__N*: Number Financings on CP  -lifetime.
- *ALLBD_mean_active_resso__N*: Average income from active contracts.
- *ALLBD_max_active_resso__N*: Maximum income from active contracts.
- *ALLBD_mean_duration_CL__N*: Average duration of CL contracts.
- *ALLBD_mean_lifecycle_CL__N*: Average lifecycle by duration on CL.
- *ALLBD_N_events__N*: Number of Contracts changes.
- *sdem_SITFAM*: Family Situation (C – married, D – divorced, S – single, U – cohabiting / partnered, V – widowed, X – other).
- *sdem_HABITAT*: Housing Situation (A – Access to property (loan), E – Housed by the employer (workplace), F – Housed by family, L – Tenant (rental), O – Other, P – Owner, X – Unknown). 
- *sdem_age*: Client's age.

### 2.1. Data Overview

Neste dataset vamos olhar para o historico do cliente e nao para o que esta ativo.

In [66]:
FAMA.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141115 entries, 0 to 141114
Data columns (total 23 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   CONTRIB                     141115 non-null  object
 1   Date_Obs                    141115 non-null  datetime64[ms]
 2   ALLBD_N_Dossiers__N         141115 non-null  float64
 3   ALLBD_N_CL__N               141115 non-null  float64
 4   ALLBD_N_CP__N               141115 non-null  float64
 5   ALLBD_A_CL__N               141115 non-null  float64
 6   ALLBD_A_CP__N               141115 non-null  float64
 7   ALLBD_MTFINO_CL__N          141115 non-null  float64
 8   ALLBD_MTFINO_CP__N          141115 non-null  float64
 9   ALLBD_MTFIN_CL__N           141115 non-null  float64
 10  ALLBD_MTFIN_CP__N           141115 non-null  float64
 11  ALLBD_IDADE_MSA__N          141115 non-null  float64
 12  ALLBD_IDADE_MIN__N          141115 non-null  float64
 13  ALLBD_IDADE_MEAN__N         141115 non-null  float64
 14  ALLBD_SUM_NUMFIN_CP__N      141115 non-null  float64
 15  ALLBD_mean_active_resso__N  141115 non-null  float64
 16  ALLBD_max_active_resso__N   141115 non-null  float64
 17  ALLBD_mean_duration_CL__N   141115 non-null  float64
 18  ALLBD_mean_lifecycle_CL__N  141115 non-null  float64
 19  ALLBD_N_events__N           141115 non-null  float64
 20  sdem_SITFAM                 141115 non-null  object
 21  sdem_HABITAT                141115 non-null  object
 22  sdem_age                    141115 non-null  int64
dtypes: datetime64[ms](1), float64(18), int64(1), object(3)
memory usage: 24.8+ MB

In [67]:
num_cols = FAMA.select_dtypes(include=['number']).columns
obj_cols = FAMA.select_dtypes(include=['object']).columns

print("Numéricas:", len(num_cols))
print("Categóricas:", len(obj_cols))

Numéricas: 19
Categóricas: 3

In [68]:
pd.set_option('display.max_columns', None)
FAMA.head()

,CONTRIB,Date_Obs,ALLBD_N_Dossiers__N,ALLBD_N_CL__N,ALLBD_N_CP__N,ALLBD_A_CL__N,ALLBD_A_CP__N,ALLBD_MTFINO_CL__N,ALLBD_MTFINO_CP__N,ALLBD_MTFIN_CL__N,ALLBD_MTFIN_CP__N,ALLBD_IDADE_MSA__N,ALLBD_IDADE_MIN__N,ALLBD_IDADE_MEAN__N,ALLBD_SUM_NUMFIN_CP__N,ALLBD_mean_active_resso__N,ALLBD_max_active_resso__N,ALLBD_mean_duration_CL__N,ALLBD_mean_lifecycle_CL__N,ALLBD_N_events__N,sdem_SITFAM,sdem_HABITAT,sdem_age
0,31f4b2a40e2cc73faf9cf16c7bd6ebeea6f322931d4e0b3ac4c2861934bdb984,2024-11-30,15.0,6.0,9.0,1.0,0.0,88784.04,0.00,88784.040000,0.0,4443.0,-808.0,1280.533333,0.0,1153.000000,1153.0,120.0,0.425000,15.0,C,P,62
1,bb7bc8dfa33e27eb832f58210a2d3282839cd2a8e7f4203e0d7e946045b89a7b,2024-11-30,6.0,4.0,2.0,1.0,2.0,9584.91,7628.41,9584.910000,0.0,3120.0,-2077.0,466.333333,14.0,1564.666667,1582.0,72.0,0.138889,6.0,C,A,65
2,a377de96fc89a1aabdb5e25682e54c7d02a7209c7246d09e751e15cf4b6c2029,2024-11-30,8.0,5.0,3.0,1.0,0.0,22000.86,0.00,22000.860000,0.0,4936.0,-2089.0,907.625000,0.0,1765.000000,1765.0,36.0,0.277778,8.0,C,L,65
3,9e4d032b84105ac4981257fc993ed33f60dfec1542c72305edb48e7f3bfa2396,2024-11-30,3.0,3.0,0.0,1.0,0.0,10384.00,0.00,10384.000000,0.0,2882.0,-2096.0,301.000000,0.0,840.000000,840.0,72.0,0.138889,3.0,V,P,69
4,7d0cb0079863cbf9d6d179491aab944c9af7e988d1e4bc19d5017c0c672a8de6,2024-11-30,9.0,8.0,1.0,1.0,0.0,12866.23,0.00,13756.584246,0.0,8629.0,-1063.0,2267.555556,0.0,3268.000000,3268.0,48.0,0.916667,9.0,C,A,68

In [69]:
FAMA.describe().T

                               count                 mean                  min                  25%                  50%                  75%                  max           std
Date_Obs                      141115  2024-11-30 00:00:00  2024-11-30 00:00:00  2024-11-30 00:00:00  2024-11-30 00:00:00  2024-11-30 00:00:00  2024-11-30 00:00:00           NaN
ALLBD_N_Dossiers__N         141115.0             8.569727                  1.0                  4.0                  7.0                 11.0                136.0       6.21527
ALLBD_N_CL__N               141115.0             5.796868                  0.0                  3.0                  5.0                  8.0                 91.0      4.768982
ALLBD_N_CP__N               141115.0             2.772859                  0.0                  1.0                  2.0                  4.0                 81.0      2.302179
ALLBD_A_CL__N               141115.0             0.782319                  0.0                  0.0                  1.0                  1.0                  7.0       0.61869
ALLBD_A_CP__N               141115.0             0.682911                  0.0                  0.0                  1.0                  1.0                  9.0       0.79483
ALLBD_MTFINO_CL__N          141115.0         17305.858039                  0.0               5000.0              11000.0             22324.89            436815.12  19565.305925
ALLBD_MTFINO_CP__N          141115.0           2890.91579                  0.0                  0.0                  0.0              3187.78            322929.95   6739.935575
ALLBD_MTFIN_CL__N           141115.0           17459.8429                  0.0               5000.0              11000.0              22500.0             996095.0  20332.811246
ALLBD_MTFIN_CP__N           141115.0            83.288209              -2649.0                  0.0                  0.0                9.485              8574.36    289.391822
ALLBD_IDADE_MSA__N          141115.0          2772.890947              -2369.0                589.0               2951.0               4778.0              16989.0   2581.333796
ALLBD_IDADE_MIN__N          141115.0         -1564.791588              -2403.0              -2217.0              -1899.0              -1311.0               7052.0   1049.676191
ALLBD_IDADE_MEAN__N         141115.0           438.160308              -2382.5              -716.75           253.785714          1411.278846               7435.5   1545.011739
ALLBD_SUM_NUMFIN_CP__N      141115.0            36.119031                  0.0                  0.0                  0.0                 18.0               9234.0    125.693948
ALLBD_mean_active_resso__N  141115.0             947.9069                  0.0                661.0                870.0               1205.0             361265.0   1220.099259
ALLBD_max_active_resso__N   141115.0           987.189172                  0.0                683.0                900.0               1258.0             361265.0   1271.391866
ALLBD_mean_duration_CL__N   141115.0            53.044695                  0.0                  0.0                 60.0                 84.0                156.0     43.292167
ALLBD_mean_lifecycle_CL__N  141115.0             0.272133                  0.0                  0.0             0.190476             0.491667               2.6875      0.283844
ALLBD_N_events__N           141115.0             8.569776                  1.0                  4.0                  7.0                 11.0                136.0      6.215371
sdem_age                    141115.0            45.049732                 18.0                 36.0                 44.0                 53.0                102.0     12.055898

In [70]:
#descriptive statistics for categorical data
FAMA.describe(include = ['O'])

                                                                 CONTRIB sdem_SITFAM sdem_HABITAT
count                                                             141115      141115       141115
unique                                                            141115           8            8
top     44ca1997fb28fe89d7114f2ff4c81d2619615bf6d5e736b451ca12a484b41973           C            A
freq                                                                   1       52752        45453

In [71]:
FAMA.shape

(141115, 23)

In [72]:
FAMA['CONTRIB'].nunique()

141115

In [73]:
FAMA['sdem_SITFAM'].value_counts(dropna=False)

sdem_SITFAM
C    52752
X    29322
S    27440
U    13184
D     9859
F     3163
P     2854
V     2541
Name: count, dtype: int64

- There are a large number of married (C), other (X), single (S) and cohabiting (U) people. 
- The least common are widowed

In [74]:
FAMA['sdem_HABITAT'].value_counts(dropna=False)

sdem_HABITAT
A    45453
F    40816
P    39321
L    14971
O      234
X      170
E      147
0        3
Name: count, dtype: int64

- Most people have access to property (loan), are housed by family and owned or rent a house.
- The least common is 'other' and housed by the employer.

### 2.2. Checking Duplicates

In [75]:
#checking number of duplicates
FAMA.duplicated().sum()

np.int64(0)

### 2.3. Checking Missing Values

In [76]:
#checking number of missing values
FAMA.isna().sum()

CONTRIB                       0
Date_Obs                      0
ALLBD_N_Dossiers__N           0
ALLBD_N_CL__N                 0
ALLBD_N_CP__N                 0
ALLBD_A_CL__N                 0
ALLBD_A_CP__N                 0
ALLBD_MTFINO_CL__N            0
ALLBD_MTFINO_CP__N            0
ALLBD_MTFIN_CL__N             0
ALLBD_MTFIN_CP__N             0
ALLBD_IDADE_MSA__N            0
ALLBD_IDADE_MIN__N            0
ALLBD_IDADE_MEAN__N           0
ALLBD_SUM_NUMFIN_CP__N        0
ALLBD_mean_active_resso__N    0
ALLBD_max_active_resso__N     0
ALLBD_mean_duration_CL__N     0
ALLBD_mean_lifecycle_CL__N    0
ALLBD_N_events__N             0
sdem_SITFAM                   0
sdem_HABITAT                  0
sdem_age                      0
dtype: int64

### 2.4. Checking Outliers

### 2.5. Checking Distribution

#### 2.5.1. Numerical Variables

#### 2.5.2. Categorical Variables

### 2.6. Checking Correlation between variables

Retirar "ALLBD_N_events__N" e "ALLBD_max_active_resso__N"

"ALLBD_MTFIN_CL__N" e "ALLBD_MTFINO_CL__N" são quase redundantes mas vão servir para criar uma variavel, depois podemos tirar

<a class="anchor" id="2.2 Analysing the Data">

## 3. Data Preparation
    
</a>

In [78]:
# proporção de créditos ativos

FAMA["active_credit_ratio"] = (
    FAMA["ALLBD_A_CL__N"] + FAMA["ALLBD_A_CP__N"]
) / (
    FAMA["ALLBD_N_CL__N"] + FAMA["ALLBD_N_CP__N"] + 1
)

0 -> nenhum credito ativo

1 -> todos os créditos estão ativos

In [79]:
# carga financeira (montante de crédito vs rendimento)
FAMA["debt_income_ratio"] = (
    FAMA["ALLBD_MTFIN_CL__N"] /
    (FAMA["ALLBD_mean_active_resso__N"] + 1)
)

In [80]:
# ratio de progresso do crédito

FAMA["credit_progress"] = (
    FAMA["ALLBD_MTFIN_CL__N"] /
    (FAMA["ALLBD_MTFINO_CL__N"] + 1)
)

In [81]:
# percentagem de credito por pagar

FAMA["credit_remaining_ratio"] = (
    FAMA["ALLBD_MTFIN_CL__N"] /
    (FAMA["ALLBD_MTFINO_CL__N"] + 1)
)

In [82]:
drop=['ALLBD_A_CL__N','ALLBD_A_CP__N','ALLBD_MTFIN_CL__N','ALLBD_MTFIN_CP__N']
drop1=['ALLBD_IDADE_MSA__N','ALLBD_IDADE_MIN__N']
FAMA= FAMA.drop(columns=drop1, errors='ignore')

In [83]:
FAMA.head()

,CONTRIB,Date_Obs,ALLBD_N_Dossiers__N,ALLBD_N_CL__N,ALLBD_N_CP__N,ALLBD_A_CL__N,ALLBD_A_CP__N,ALLBD_MTFINO_CL__N,ALLBD_MTFINO_CP__N,ALLBD_MTFIN_CL__N,ALLBD_MTFIN_CP__N,ALLBD_IDADE_MEAN__N,ALLBD_SUM_NUMFIN_CP__N,ALLBD_mean_active_resso__N,ALLBD_max_active_resso__N,ALLBD_mean_duration_CL__N,ALLBD_mean_lifecycle_CL__N,ALLBD_N_events__N,sdem_SITFAM,sdem_HABITAT,sdem_age,active_credit_ratio,debt_income_ratio,credit_progress,credit_remaining_ratio
0,31f4b2a40e2cc73faf9cf16c7bd6ebeea6f322931d4e0b3ac4c2861934bdb984,2024-11-30,15.0,6.0,9.0,1.0,0.0,88784.04,0.00,88784.040000,0.0,1280.533333,0.0,1153.000000,1153.0,120.0,0.425000,15.0,C,P,62,0.062500,76.935910,0.999989,0.999989
1,bb7bc8dfa33e27eb832f58210a2d3282839cd2a8e7f4203e0d7e946045b89a7b,2024-11-30,6.0,4.0,2.0,1.0,2.0,9584.91,7628.41,9584.910000,0.0,466.333333,14.0,1564.666667,1582.0,72.0,0.138889,6.0,C,A,65,0.428571,6.121935,0.999896,0.999896
2,a377de96fc89a1aabdb5e25682e54c7d02a7209c7246d09e751e15cf4b6c2029,2024-11-30,8.0,5.0,3.0,1.0,0.0,22000.86,0.00,22000.860000,0.0,907.625000,0.0,1765.000000,1765.0,36.0,0.277778,8.0,C,L,65,0.111111,12.458018,0.999955,0.999955
3,9e4d032b84105ac4981257fc993ed33f60dfec1542c72305edb48e7f3bfa2396,2024-11-30,3.0,3.0,0.0,1.0,0.0,10384.00,0.00,10384.000000,0.0,301.000000,0.0,840.000000,840.0,72.0,0.138889,3.0,V,P,69,0.250000,12.347206,0.999904,0.999904
4,7d0cb0079863cbf9d6d179491aab944c9af7e988d1e4bc19d5017c0c672a8de6,2024-11-30,9.0,8.0,1.0,1.0,0.0,12866.23,0.00,13756.584246,0.0,2267.555556,0.0,3268.000000,3268.0,48.0,0.916667,9.0,C,A,68,0.100000,4.208193,1.069118,1.069118

In [84]:
x = (FAMA['ALLBD_mean_active_resso__N'] != FAMA['ALLBD_max_active_resso__N']).mean() * 100
x

np.float64(21.01973567657584)

<div class="alert alert-block alert-info">

<a class="anchor" id="2. Data Exploration">    </a>
# BDOSS Dataset
       
</div>

<a class="anchor" id="2.2 Analysing the Data">

## 2. Analysing the Data
    
</a>

#### 2.2.4.1. Data Overview

In [85]:
pd.set_option('display.max_columns', None)
BDOSS.head()

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,MENSALIDADE_CORR,CRD,SREC,ACTIVIDADE_GLOBAL,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO
0,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0.0,ENC,2024-01-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120.0,69.0,69.0,20000.0,20000.0,347.447280,NaN,13208.455,0.000,NaN,0.0,0.0,000000000000000000000000,0.0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A
1,0000e359b15a80ba12c7f60c0fe06ffc68621c87f13a4f88f54188543d9a09c8,b83e6ef0c9c12f8304d86c40458a5b88ec72e534201c32a1a99618e5be83ced1,P,CL,EP,0.0,SAN,2024-01-31,2019-01-28,2019-02-04,2019-02-04,2022-12-28,72.0,34.0,34.0,2500.0,2500.0,56.017772,NaN,0.000,0.000,NaN,1.0,1.0,000000000000210210000110,0.0,120.0,N,838.186,91.0,1990.0,P,2855,0.0,A
2,0000f858346061c53064586a3347b34659565a6712d004e64309c2473f76faed,29c3cfb34c4e2ecd6749b0c1a6205dfce33c0e717514560542d65af5e63e2157,P,CL,EP,0.0,ENC,2024-01-31,2019-09-23,2019-09-30,2019-09-30,2019-09-30,84.0,52.0,52.0,5000.0,5000.0,100.073575,NaN,2665.191,0.000,NaN,0.0,0.0,000000000000000000000000,0.0,118.0,P,1314.144,80.0,2013.0,P,2635,2.0,W
3,00025459b703e1c308553e83a6d545a71fe6a787c2dd1c62d26faa0207cc5b08,446d96905d26356fb4f1d3e1e6da3868b8106b09a558e61d70dcb3944412ecac,P,CL,EPF,0.0,ENC,2024-01-31,2023-01-09,2023-01-13,2023-01-13,2023-01-13,60.0,13.0,37.0,6000.0,6000.0,162.097525,NaN,5893.092,0.000,NaN,0.0,0.0,000000000000000000000000,0.0,117.0,P,1031.650,80.0,1989.0,P,5090,0.0,A
4,00041ebafb1270a818c30cb1fb20d3699002196644ea8fd9df9425df6f49db00,26d59ea8a93be739e9fc4a0404f07c73aae276243e5cd6236580eb19aa138a56,N,CL,EXT,0.0,ENC,2024-01-31,2021-02-10,2021-02-17,2021-02-17,2024-01-31,84.0,32.0,32.0,20500.0,20500.0,463.755537,NaN,17844.618,-463.756,NaN,2.0,4.0,000000000000000002112122,0.0,119.0,P,1113.258,80.0,2019.0,P,2835,0.0,A

In [86]:
BDOSS.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2658187 entries, 0 to 2658186
Data columns (total 35 columns):
 #   Column             Dtype
---  ------             -----
 0   CONTRIB            object
 1   DOSSIER            object
 2   POLE               object
 3   TYPEPROD           object
 4   PRODALP            object
 5   BICONTRATO         float64
 6   POS                object
 7   OBS_DATE           datetime64[ns]
 8   DCREAT             datetime64[ns]
 9   DATFIN             datetime64[ns]
 10  D1FIN              datetime64[ns]
 11  DPOS               datetime64[ns]
 12  DURDEG             float64
 13  RANGPRO            float64
 14  RANGCLI            float64
 15  MTFINO             float64
 16  MTFIN              float64
 17  MENSALIDADE        float64
 18  MENSALIDADE_CORR   float64
 19  CRD                float64
 20  SREC               float64
 21  ACTIVIDADE_GLOBAL  float64
 22  RN                 float64
 23  RD                 float64
 24  RISK               object
 25  RISKA              float64
 26  AGFIN              float64
 27  PAGAMENTO          object
 28  RESSO              float64
 29  CSP                float64
 30  DCSP               float64
 31  NATIO              object
 32  PTT                object
 33  NBENF              float64
 34  MODCONTACTO        object
dtypes: datetime64[ns](5), float64(19), object(11)
memory usage: 709.8+ MB

In [87]:
BDOSS['BICONTRATO'] = BDOSS['BICONTRATO'].round().astype('Int32')
BDOSS['DURDEG'] = BDOSS['DURDEG'].round().astype('Int32')
BDOSS['RANGPRO'] = BDOSS['RANGPRO'].round().astype('Int32')
BDOSS['RANGCLI'] = BDOSS['RANGCLI'].round().astype('Int32')
BDOSS['RISKA'] = BDOSS['RISKA'].round().astype('Int32')

In [88]:
BDOSS.describe(include='all').T

,count,unique,top,freq,mean,min,25%,50%,75%,max,std
CONTRIB,2658187,148729,364aad4f1733591b129753f295cca317a449f207c209bdc4db94c94e6646dde6,158,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DOSSIER,2658187,185592,f8908577ee5bab0f764f1f007f439370b0511585b89d96f41bf1a00cffdddea9,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN
POLE,2658187,2,P,2615205,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TYPEPROD,2658187,1,CL,2658187,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PRODALP,2658187,4,EP,1912612,NaN,NaN,NaN,NaN,NaN,NaN,NaN
BICONTRATO,2658187.0,<NA>,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0
POS,2658187,4,ENC,2214397,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OBS_DATE,2658187,NaN,NaN,NaN,2024-12-31 12:04:59.079635456,2024-01-31 00:00:00,2024-06-30 00:00:00,2024-12-31 00:00:00,2025-06-30 00:00:00,2025-11-30 00:00:00,NaN
DCREAT,2658187,NaN,NaN,NaN,2022-03-23 09:42:27.446511104,1996-06-14 00:00:00,2020-11-24 00:00:00,2022-10-20 00:00:00,2024-01-31 00:00:00,2025-12-02 00:00:00,NaN
DATFIN,2658187,NaN,NaN,NaN,2022-04-01 11:27:02.187001088,1996-06-17 00:00:00,2020-12-02 00:00:00,2022-10-28 00:00:00,2024-02-07 00:00:00,2025-12-02 00:00:00,NaN
D1FIN,2658187,NaN,NaN,NaN,2022-03-31 20:48:34.581405184,1996-06-14 00:00:00,2020-12-02 00:00:00,2022-10-28 00:00:00,2024-02-07 00:00:00,2025-12-02 00:00:00,NaN
DPOS,2658187,NaN,NaN,NaN,2023-03-13 07:10:07.502632960,2014-06-27 00:00:00,2022-03-08 00:00:00,2023-10-31 00:00:00,2024-09-16 00:00:00,2025-12-02 00:00:00,NaN
DURDEG,2658187.0,<NA>,<NA>,<NA>,75.022708,11.0,48.0,84.0,84.0,156.0,29.54134
RANGPRO,2658187.0,<NA>,<NA>,<NA>,30.018862,0.0,10.0,24.0,46.0,120.0,23.980026
RANGCLI,2658186.0,<NA>,<NA>,<NA>,43.088744,0.0,23.0,39.0,61.0,400.0,26.936884
MTFINO,2658187.0,NaN,NaN,NaN,9852.417575,300.0,4000.0,7000.0,13000.0,85096.65,8858.97092
MTFIN,2658187.0,NaN,NaN,NaN,9852.601694,300.0,4000.0,7000.0,13000.0,85096.65,8859.030743
MENSALIDADE,2658187.0,NaN,NaN,NaN,215.405474,0.180766,106.121286,164.009111,268.914138,6346.5888,171.858686
MENSALIDADE_CORR,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CRD,2658187.0,NaN,NaN,NaN,6889.87035,0.0,1067.088,4190.803,9311.082,106785.113,8521.446921
SREC,2658187.0,NaN,NaN,NaN,-5.218167,-4934.458,0.0,0.0,0.0,75010.83,288.578966
ACTIVIDADE_GLOBAL,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RN,2658187.0,NaN,NaN,NaN,0.214033,0.0,0.0,0.0,0.0,6.0,0.591448
RD,2658187.0,NaN,NaN,NaN,0.72898,0.0,0.0,0.0,0.0,12.0,2.289499
RISK,2658187,77475,000000000000000000000000,2327930,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RISKA,2658187.0,<NA>,<NA>,<NA>,0.050694,0.0,0.0,0.0,0.0,7.0,0.416893
AGFIN,2658187.0,NaN,NaN,NaN,124.235698,100.0,117.0,118.0,119.0,525.0,49.322618
PAGAMENTO,2658187,3,P,2635902,NaN,NaN,NaN,NaN,NaN,NaN,NaN
RESSO,2658187.0,NaN,NaN,NaN,1482.108494,0.0,977.381,1230.628,1738.741,1665025.598,3801.121102
CSP,2658187.0,NaN,NaN,NaN,62.336617,0.0,55.0,60.0,80.0,99.0,20.60364
DCSP,2364524.0,NaN,NaN,NaN,2009.717662,1000.0,2002.0,2013.0,2018.0,2025.0,10.738669
NATIO,2658186,4,P,2632958,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PTT,2658187,763,2735,30609,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NBENF,2657451.0,NaN,NaN,NaN,0.622201,0.0,0.0,0.0,1.0,90.0,0.848657
MODCONTACTO,2598643,6,W,1483323,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 2.2.4.2. Checking Duplicates

In [89]:
BDOSS.duplicated().sum()

np.int64(0)

#### 2.2.4.3. Checking Missing Values

In [90]:
BDOSS.isna().sum()[BDOSS.isna().sum() > 0]

RANGCLI                    1
MENSALIDADE_CORR     2658187
ACTIVIDADE_GLOBAL    2658187
DCSP                  293663
NATIO                      1
NBENF                    736
MODCONTACTO            59544
dtype: int64

In [91]:
#checking number of missing values in each column as a percentage
BDOSS.isna().sum()[BDOSS.isna().sum() > 0]/len(BDOSS) * 100

RANGCLI                0.000038
MENSALIDADE_CORR     100.000000
ACTIVIDADE_GLOBAL    100.000000
DCSP                  11.047492
NATIO                  0.000038
NBENF                  0.027688
MODCONTACTO            2.240023
dtype: float64

**- Constant Features**

In [92]:
BDOSS['MENSALIDADE_CORR'].unique()

array([nan])

In [93]:
BDOSS['ACTIVIDADE_GLOBAL'].unique()

array([nan])

In [94]:
BDOSS['TYPEPROD'].unique()

array(['CL'], dtype=object)

In [95]:
BDOSS['BICONTRATO'].unique()

<IntegerArray>
[0]
Length: 1, dtype: Int32

**- more data analysis**

In [96]:
BDOSS['RISK'].value_counts()

RISK
000000000000000000000000    2327930
444444444444444444444444      23863
000000000000000000000001      16652
000000000000000000000010       7487
000000000000000000000100       6278
                             ...
010000100001000111122010          1
000000100000000010101010          1
012222222122221221111221          1
000001122222221221122100          1
000110210110000000211221          1
Name: count, Length: 77475, dtype: int64

In [97]:
BDOSS['RISKA'].value_counts()

RISKA
0    2571156
1      79077
7       7954
Name: count, dtype: Int64

In [98]:
BDOSS['NBENF'].value_counts()

NBENF
0.0     1538648
1.0      664154
2.0      385790
3.0       59785
4.0        7713
5.0        1288
8.0          23
7.0          23
10.0         11
52.0          8
6.0           6
90.0          2
Name: count, dtype: int64

In [99]:
BDOSS['AGFIN'].value_counts()

AGFIN
118.0    1229325
117.0     720161
120.0     518201
119.0     146805
525.0      39560
112.0       3963
111.0         66
500.0         48
503.0         46
116.0          6
100.0          6
Name: count, dtype: int64

In [100]:
BDOSS['POS'].unique()

array(['ENC', 'SAN', 'SOL', 'RBT'], dtype=object)

Meanings of POS's unique values:
- ENC: Normal state;
- SAN: Client settles before date;
- SOL: Client settles on contract termination date;
- RBT: Same as SAN (business wise).

Since RBT is the same as SAN, we will update our dataset so that every RBT turns into SAN.

In [101]:
BDOSS['POS'] = BDOSS['POS'].replace('RBT', 'SAN')

In [102]:
BDOSS['RN'].value_counts()

RN
0.0    2270299
1.0     257370
2.0      88703
3.0      34114
4.0       6707
5.0        970
6.0         24
Name: count, dtype: int64

RN is a red flag feature, the higher it's value, the higher the chance a client will churn.

In [103]:
BDOSS['POLE'].value_counts()

POLE
P    2615205
N      42982
Name: count, dtype: int64

Not specified in MetaData, however, we were told that:
- P: Direct business;
- N: Sales for business partners.

#### 2.2.1.4. Checking Incoherencies

**- PRODALP**

In [104]:
BDOSS['PRODALP'].value_counts()

PRODALP
EP     1912612
EPF     394887
EXT     287176
DEF      63512
Name: count, dtype: int64

None of these unique values appear in our MetaData. However, we were told that:
- EP - most used when the clients want to churn; 
- EXT, EPF, DEF: Personal loans.

**- CSP**

In [105]:
BDOSS['CSP'].unique()

array([80., 91., 35., 60., 90., 54., 70., 31., 74., 20., 58., 15., 41.,
       10., 50., 33., 56., 55., 86., 32., 30., 92., 57., 52., 53., 34.,
       40., 81., 99.,  0., 96., 25., 51.])

The values 54, 58, 50, 56, 55, 57, 52, 53, 0 and 51 also don't appear in our MetaData.

In [106]:
missing = [54, 58, 50, 56, 55, 57, 52, 53, 0, 51]
result = 0
for num in BDOSS['CSP']:
    if num in missing:
        result = result + 1
print(result)

161453

In [107]:
result / len(BDOSS['CSP']) * 100

6.073801429320059

These values correspond to around 6% of our data

**- RISK AND RISKA**

In [108]:
BDOSS[BDOSS['RISKA'] != BDOSS['RISK'].astype(str).str[-1].astype(int)]

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,MENSALIDADE_CORR,CRD,SREC,ACTIVIDADE_GLOBAL,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO
4,00041ebafb1270a818c30cb1fb20d3699002196644ea8fd9df9425df6f49db00,26d59ea8a93be739e9fc4a0404f07c73aae276243e5cd6236580eb19aa138a56,N,CL,EXT,0,ENC,2024-01-31,2021-02-10,2021-02-17,2021-02-17,2024-01-31,84,32,32,20500.0,20500.0,463.755537,NaN,17844.618,-463.756,NaN,2.0,4.0,000000000000000002112122,0,119.0,P,1113.258,80.0,2019.0,P,2835,0.0,A
53,00245abdde6b5be044bd121c4618fdcc43e90f9f0ef5bccd4bf8dce4665e2303,64f6c53b0b8e111e029da5ea073196dbd89ae6025fd9a71125070fca88f38625,P,CL,EP,0,SAN,2024-01-31,2022-12-29,2023-01-05,2023-01-05,2023-12-11,22,11,11,2500.0,2500.0,147.925036,NaN,0.000,0.000,NaN,1.0,3.0,000000000000020000101011,0,118.0,P,1451.493,80.0,2021.0,D,8125,2.0,W
57,0026b5f0de9828ec21d97c586dc791fb0671a0224617d1aa20e6edf4ce631f4e,2b075e5032a850f4290d1b23e68320cd36cffb93f7dcc8215e7c6ed10b3824e0,P,CL,EP,0,SAN,2024-01-31,2022-02-02,2022-02-03,2022-02-03,2023-06-05,60,16,37,2500.0,2500.0,61.538164,NaN,0.000,0.000,NaN,3.0,9.0,000000002110122200122001,0,118.0,P,2009.717,10.0,2018.0,P,3090,2.0,W
72,002ddf74dace98336bfd869bdf44deab63ab07753122d6336e1076b940009faa,2a0c6243fee831fa936fc507b331b614dc6ad6b53910d6096b2c457312479cbf,P,CL,EP,0,SOL,2024-01-31,2014-01-09,2014-01-22,2014-01-09,2022-10-04,84,81,81,5000.0,5000.0,118.518615,NaN,0.000,0.000,NaN,3.0,5.0,221111222112012212220111,0,119.0,P,1231.996,70.0,2009.0,P,7580,0.0,T
122,004cc9fa8892482a26231071d03ecb17c5a8779b683804c9075c7dc0ea10a89d,56ca44ed01b953656bd0b46454b894de6b39d882e52279491e084250263da9eb,P,CL,EXT,0,ENC,2024-01-31,2023-04-26,2023-05-08,2023-05-05,2024-01-23,84,9,9,10343.0,10343.0,233.912421,NaN,11549.523,0.000,NaN,0.0,0.0,000000000000000000010110,1,118.0,P,2523.423,35.0,2009.0,P,2775,2.0,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2658123,ffddc57160d56f6899d2daa5e1a1720b5903a6e665354fc5e1bda5faa6d8f7ed,c56d1af3fdeeceb79806b8dd25b0495f25f225b5428e88b488381acf4dcddb37,P,CL,EPF,0,ENC,2025-11-30,2022-01-09,2022-02-16,2022-02-16,2024-09-09,84,45,45,5000.0,5000.0,107.643659,NaN,3307.841,0.000,NaN,0.0,0.0,000010000000000000000000,1,118.0,P,313.084,52.0,NaN,P,2415,0.0,W
2658149,ffec38e28088b6290ec9ed851675f19b0182cecd14a105eb3fd58866e690bea5,7bcb4d654fd5736dcc83846e861dfb7b2fab4b21bf7180f81105384e50823e06,P,CL,EPF,0,ENC,2025-11-30,2022-10-06,2022-10-14,2022-10-14,2025-11-28,84,38,38,11000.0,11000.0,244.084787,NaN,8467.150,0.000,NaN,0.0,0.0,000000000010001000000101,0,117.0,P,861.102,80.0,2000.0,P,3720,0.0,A
2658180,fffa9b9225bff7296ad890805ea9ccf9a105663acb1a976298f14134a4b0a710,9638a80107e20c8cbf33e66fe0ffc642fee561907852dc721ebe503a221d6a1d,P,CL,EXT,0,SAN,2025-11-30,2023-08-01,2023-08-21,2023-08-18,2025-08-12,84,23,23,24750.0,24750.0,584.152276,NaN,0.000,0.000,NaN,0.0,0.0,000000000000000001111111,0,118.0,P,1253.882,80.0,1995.0,P,4425,1.0,W
2658183,fffbc66ca4256976c9932916770f1ff3b23aacce5998ffc7d570a73378d619df,dea39098d015a030ea0b3ead87c82ccca9137f784f86c7a4e15a2b1365e14fd8,P,CL,EPF,0,ENC,2025-11-30,2018-12-21,2018-12-24,2018-12-24,2025-11-28,84,83,83,7430.0,7430.0,157.667572,NaN,137.403,-157.668,NaN,1.0,2.0,000000000000002001111112,0,118.0,P,977.381,31.0,2018.0,P,4820,1.0,W
2658185,fffc47b191b25cbc3dbc9ce436b94e52d2084144ee5bec31fd2457f3cff87c3c,43fefbb99328741294aa67fa5bb29cdaf0acff276e282dcfdd480b63fd6b0eb2,P,CL,EP,0,ENC,2025-11-30,2025-05-29,2025-06-02,2025-06-02,2025-11-25,36,6,6,2000.0,2000.0,81.856368,NaN,1994.881,13.462,NaN,0.0,0.0,000000000000000000000011,0,120.0,P,0.000,80.0,2007.0,P,4485,2.0,W

In [109]:
168528 / len(BDOSS) * 100

6.339960281199178

Here, we can see that only around 6% of our data has a RISKA value diferent than the last number of RISK.

In [110]:
mask = BDOSS['RISKA'] != BDOSS['RISK'].astype(str).str[-1].astype(int)

BDOSS.loc[mask, 'RISK'] = (BDOSS.loc[mask, 'RISK'].astype(str).str[:-1] + 
                           BDOSS.loc[mask, 'RISKA'].astype(str))

BDOSS[BDOSS['RISKA'] != BDOSS['RISK'].astype(str).str[-1].astype(int)]

Empty DataFrame
Columns: [CONTRIB, DOSSIER, POLE, TYPEPROD, PRODALP, BICONTRATO, POS, OBS_DATE, DCREAT, DATFIN, D1FIN, DPOS, DURDEG, RANGPRO, RANGCLI, MTFINO, MTFIN, MENSALIDADE, MENSALIDADE_CORR, CRD, SREC, ACTIVIDADE_GLOBAL, RN, RD, RISK, RISKA, AGFIN, PAGAMENTO, RESSO, CSP, DCSP, NATIO, PTT, NBENF, MODCONTACTO]
Index: []

As we can see from the cell above, every one of those referenced entries were corrected so that every RISKA value corresponds to the last number of it's respective RISK value.

**- RANGPRO AND DURDEG**

In [111]:
BDOSS[BDOSS['RANGPRO'] - BDOSS['DURDEG'] > 0]

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,MENSALIDADE_CORR,CRD,SREC,ACTIVIDADE_GLOBAL,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO
13373,1eeda66678fe87887b4e435aa1ac405c4ee922ad6bed980a526af9c162868c11,6a73d420a9c4629486e6f5dda41f27e14de45734f835ab26a77b84c1a5626065,P,CL,EP,0,SOL,2024-01-31,2017-09-14,2017-09-21,2017-09-21,2023-12-01,72,73,73,7000.00,7000.00,157.190164,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1181.441,70.0,1987.0,P,2350,0.0,A
14809,22535d3248147b8e894c46602e349876a2b7a58252a7b07a61181680ff2f5d99,d55babf7dbe197586e7b624efb0da2d1898a90f918b7acaf380e210eaf2096e7,P,CL,EPF,0,SOL,2024-01-31,2015-05-22,2015-05-28,2015-05-22,2023-08-04,84,85,85,9000.46,9000.46,199.519797,NaN,0.0,0.0,NaN,1.0,1.0,100000000000000121212120,0,118.0,N,1851.117,90.0,2000.0,P,3610,1.0,None
23704,366d5bd958989f93f6e20d957959f964ddf065149bd715a8f3d1fac7ac3d88c5,7e205ecd82246afc84cc94105be457755e0fe7ccd65b2f3ed9dd5bb5eb5345e2,P,CL,EPF,0,SOL,2024-01-31,2016-08-08,2016-08-23,2016-08-08,2023-11-21,84,85,85,10500.00,10500.00,238.839973,NaN,0.0,0.0,NaN,1.0,0.0,000000110100200111000010,0,117.0,P,901.600,70.0,2012.0,P,2410,1.0,None
48850,7013a45ea15ab41a281691a85a99c53bb650d7b6d127450dbd93fedd33a7a417,e0cfdfb6402b13a9540add0d348ad1d166ff5de5b99d1f0514824286fc1753f5,P,CL,EPF,0,SOL,2024-01-31,2016-10-14,2016-10-24,2016-10-14,2024-01-01,84,85,85,15000.60,15000.60,341.476332,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000001000000,0,117.0,P,836.839,80.0,1993.0,P,7370,0.0,None
53702,7b2db95efe1f3f55ae0566731a18ef153f7ada276c4fc3bbfab60ea391c7c013,7c2e2cb7b349743596bd6087f9b55d20d0d2ffae927505635daee5cfbb50410f,P,CL,EP,0,SOL,2024-01-31,2017-10-03,2017-10-09,2017-10-09,2024-01-01,72,73,73,15000.00,15000.00,344.638483,NaN,0.0,0.0,NaN,0.0,0.0,000000000000010000000000,0,118.0,P,1045.234,60.0,2012.0,P,2675,0.0,W
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591774,747283c8dd6c2be7c5e4d86c4adcd653c3f9381b4f0e6af86bcecb096604efc8,66bb8e8c16bac641e2ff3f1cfbb4f760c310ae3c652d9e9c4be74e349fc41cfb,P,CL,EP,0,SOL,2025-11-30,2017-05-06,2017-07-12,2017-07-12,2025-09-10,96,97,97,25000.00,25000.00,476.003055,NaN,0.0,0.0,NaN,1.0,2.0,002210000000000000002210,0,118.0,P,2710.636,81.0,2016.0,P,2430,2.0,W
2592547,761e197ef3212fef89be1a88eb9d46d862c72e699dc9f6b117211e6506ea3af3,91f180eb8d37733c4bd4a1c1f40cce541a84039790e78d40a9e5e36bb23cec08,P,CL,EP,0,SOL,2025-11-30,2019-07-02,2019-07-08,2019-07-08,2025-10-01,72,73,73,11000.00,11000.00,248.800673,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,662.454,20.0,2015.0,P,4500,2.0,A
2595126,7b4ae59459f74157e8dd76f2cb2a4418dae8818d89758c0e7b659faaa7a25317,735d4904fb0d6a5daf2298cd7a3f1c6d2e419fc470ea3c0c858ac20a205e9c0b,P,CL,EP,0,SOL,2025-11-30,2023-08-31,2023-08-31,2023-08-31,2025-09-05,24,25,25,4000.00,4000.00,215.810828,NaN,0.0,0.0,NaN,2.0,7.0,020000000000000000000100,0,117.0,P,1238.833,74.0,2017.0,P,9300,1.0,A
2632092,c91a7037a2ec427dfb5398e8db01c486ae872b2604c0a57bb0b84042a5366e01,4f998ab6e24407fc3d5259d9de75fa9146bc833541686e32d7924603260b7fbb,P,CL,EPF,0,SOL,2025-11-30,2019-04-29,2019-04-29,2019-04-29,2025-08-11,72,73,73,16000.00,16000.00,374.958776,NaN,0.0,0.0,NaN,0.0,0.0,000000010000000000000000,0,118.0,P,2993.089,31.0,1998.0,P,3870,1.0,A
2652606,f43c6aa26cf8198aabf0db22fc736a6fbb5118f2b24ee273884db4af3b6f466e,f4d6f484870e8ddee239bf4c4697778ca7047c77599266b7834368931141e81d,P,CL,EP,0,SOL,2025-11-30,2017-09-04,2017-09-13,2017-09-13,2025-06-09,84,85,85,5400.00,5400.00,98.813481,NaN,0.0,0.0,NaN,1.0,12.0,443344444444444444444440,0,120.0,P,2076.643,90.0,2016.0,P,2745,0.0,W

In [112]:
BDOSS[BDOSS['RANGPRO'] - BDOSS['DURDEG'] == 0]

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,MENSALIDADE_CORR,CRD,SREC,ACTIVIDADE_GLOBAL,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO
7,000607d1adce7aa9ac87274d1a2ffa84e240188de0872fc2cc3dc05d70d63560,a23e77794a2b9ab78303d8c540bd7f73ac3e3fce788fcaa0a0120c5da8a52764,P,CL,EP,0,SOL,2024-01-31,2018-07-31,2018-08-17,2018-08-17,2023-09-01,60,60,60,5000.0,5000.0,128.983684,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,912.411,60.0,2000.0,P,9680,2.0,A
80,00373284a84ad063cf446d3ddcd3b581093360d90f868dbccf24b86489105fe7,4f54a4a12cc205c0486eab64b9cc3b88f64f3d0d331684414a9b5d9e0a7f98a4,P,CL,EP,0,SOL,2024-01-31,2019-11-15,2019-11-18,2019-11-18,2023-12-01,48,48,48,4000.0,4000.0,120.673502,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,4075.148,60.0,2004.0,P,4405,0.0,A
82,0037926b6b79ef354a08b184866c44f60dcdb4c9e6bbce79d216d8235476a874,e168885d792bd5b71ded787bc796f50c8715e6519fd380b458aa6e0fb947bdda,P,CL,EP,0,SOL,2024-01-31,2022-01-31,2022-02-04,2022-02-04,2024-02-01,24,24,24,2550.0,2550.0,130.562159,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1030.291,60.0,2021.0,P,2655,0.0,W
84,003847aa9634135bca3145e5a494f81bdf3d888e97b26cf517fb2321c9e61a71,2ac8e2bbefdaf86ad0adad6350d0a3631b0dc97506eceeae5e65a5e7a68cc2dd,P,CL,EP,0,SOL,2024-01-31,2019-04-12,2019-04-16,2019-04-16,2024-01-02,56,56,56,10000.0,10000.0,247.929850,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2503.747,60.0,2015.0,P,2675,0.0,W
152,006035d67ee018b0ef98b09a75b921601bb8eebb76b44caa0ca71c173b4b7393,e9a06a469636f9dd6a20ba110a7b3bfbfcce301d3d485da081ca5ac3cc4c14dd,P,CL,EP,0,SOL,2024-01-31,2018-02-06,2018-02-12,2018-02-12,2024-02-01,72,72,72,2500.0,2500.0,57.396444,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,831.451,86.0,1998.0,P,4595,0.0,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2658094,ffce63610dbb460be5181d993711dce04a91258e18659ef32c2909162dcd0f79,7419ce475632f1f2cea9cd315bb5d001cc9fa36a1cf009c09b7a4eb2446efa3d,P,CL,EP,0,SOL,2025-11-30,2023-01-17,2023-02-01,2023-02-01,2025-08-01,30,30,73,1500.0,1500.0,68.447232,NaN,0.0,0.0,NaN,1.0,8.0,000000000000000000000000,0,118.0,P,1115.982,60.0,2022.0,P,9500,0.0,W
2658109,ffd469fd2b43c5de080a48312af88069823680eb1d86f2a00e7128ced991322d,5e853d677ae5d207d07ff52d5c43b82e7407f8c516101fa2677e1a7fd32cd0af,P,CL,EP,0,SOL,2025-11-30,2023-08-10,2023-08-14,2023-08-14,2025-08-01,24,24,24,5500.0,5500.0,311.509961,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1582.440,74.0,1994.0,P,2970,2.0,W
2658137,ffe7a79c9555711286b52c99ddae968134558142c6400d4e36fefaf39005e11d,98d451dabef588274b9eef60a64943a5370a5ed22f2915969236e29890ca51b9,P,CL,EP,0,SOL,2025-11-30,2018-06-10,2018-07-16,2018-07-16,2025-08-01,84,84,84,7000.0,7000.0,132.402437,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,694.528,31.0,2017.0,P,4560,2.0,W
2658162,fff437ed8b6c8eb46dee5ab5968d2abb4eabd769eac974278f206402a109576d,c267c3b05999dfecbdc5b40c725b6611982fb0f02bf2dc60608b8597d9c478dc,P,CL,EP,0,SOL,2025-11-30,2023-02-09,2023-03-06,2023-03-06,2025-09-01,30,30,30,2500.0,2500.0,115.844357,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1495.553,80.0,2022.0,P,6060,1.0,W
2658175,fff9552a43b3845948f34e546b8d58fd0b826ab75fe70932d6af3cf1829c0990,efdb483a2dae6d4970107039bb909441c1f710162b1972f3153332fec9133b8b,P,CL,EP,0,SOL,2025-11-30,2020-08-14,2020-08-18,2020-08-18,2025-09-01,60,60,73,5000.0,5000.0,118.270047,NaN,0.0,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2662.728,91.0,NaN,P,2580,0.0,W

In the cells above, we can see that there are 253 rows in BDOSS with a RANGPRO value higher than it's respective DURDEG value. We can also see that this diference is exactly 1 in every row.

In [113]:
mask = (BDOSS['RANGPRO'] == BDOSS['DURDEG'] + 1)
BDOSS.loc[mask, 'RANGPRO'] = BDOSS.loc[mask, 'DURDEG']
#BDOSS.loc[mask, 'DURDEG'] = BDOSS.loc[mask, 'RANGPRO']

To correct this incoherence, we decided to equalize the values.

<a class="anchor" id="2.2 Analysing the Data">

## 3. Data Preparation
    
</a>

**Feature Engineering**

as linhas que estao a 0 a mais no CRD tem que ser apagadas

In [114]:
BDOSS[BDOSS['CONTRIB']=='0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5']

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,MENSALIDADE_CORR,CRD,SREC,ACTIVIDADE_GLOBAL,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO
6,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,ENC,2024-01-31,2019-06-14,2019-06-28,2019-06-28,2019-06-28,72,55,55,5000.0,5000.0,102.689443,NaN,1652.349,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W
112231,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,SAN,2024-02-29,2019-06-14,2019-06-28,2019-06-28,2024-02-07,72,55,55,5000.0,5000.0,102.689443,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W
226260,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,SAN,2024-03-31,2019-06-14,2019-06-28,2019-06-28,2024-02-07,72,55,55,5000.0,5000.0,102.689443,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W
342751,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,SAN,2024-04-30,2019-06-14,2019-06-28,2019-06-28,2024-02-07,72,55,55,5000.0,5000.0,102.689443,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W
459541,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,SAN,2024-05-31,2019-06-14,2019-06-28,2019-06-28,2024-02-07,72,55,55,5000.0,5000.0,102.689443,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W
576867,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,SAN,2024-06-30,2019-06-14,2019-06-28,2019-06-28,2024-02-07,72,55,55,5000.0,5000.0,102.689443,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W
694271,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,SAN,2024-07-31,2019-06-14,2019-06-28,2019-06-28,2024-02-07,72,55,55,5000.0,5000.0,102.689443,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W
1044465,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2024-10-31,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,0,56,3000.0,3000.0,110.832043,NaN,3520.981,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1158889,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2024-11-30,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,0,56,3000.0,3000.0,110.832043,NaN,3520.981,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1273314,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2024-12-31,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,1,56,3000.0,3000.0,110.832043,NaN,3434.892,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1387257,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2025-01-31,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,2,56,3000.0,3000.0,110.832043,NaN,3348.140,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1497668,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,SAN,2025-02-28,2024-11-12,2024-11-18,2024-11-18,2025-02-10,36,2,56,3000.0,3000.0,110.832043,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1608541,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,SAN,2025-03-31,2024-11-12,2024-11-18,2024-11-18,2025-02-10,36,2,56,3000.0,3000.0,110.832043,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1720704,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,SAN,2025-04-30,2024-11-12,2024-11-18,2024-11-18,2025-02-10,36,2,56,3000.0,3000.0,110.832043,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1833530,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,SAN,2025-05-31,2024-11-12,2024-11-18,2024-11-18,2025-02-10,36,2,56,3000.0,3000.0,110.832043,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1947924,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,SAN,2025-06-30,2024-11-12,2024-11-18,2024-11-18,2025-02-10,36,2,56,3000.0,3000.0,110.832043,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
2063129,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,SAN,2025-07-31,2024-11-12,2024-11-18,2024-11-18,2025-02-10,36,2,56,3000.0,3000.0,110.832043,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
2179819,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-08-31,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,0,56,10500.0,10500.0,165.682282,NaN,12636.101,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W
2297362,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-09-30,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,1,56,10500.0,10500.0,165.682282,NaN,12566.088,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W
2416440,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-10-31,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,2,56,10500.0,10500.0,165.682282,NaN,12495.616,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W
2537003,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-11-30,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,3,56,10500.0,10500.0,148.056088,NaN,12424.673,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W

In [115]:
# garantir ordem temporal
BDOSS = BDOSS.sort_values(['CONTRIB', 'DOSSIER', 'OBS_DATE']).copy()

# contar quantas vezes já apareceu CRD == 0 dentro de cada contrato
zero_count = (
    BDOSS['CRD'].eq(0)
    .groupby([BDOSS['CONTRIB'], BDOSS['DOSSIER']])
    .cumsum()
)

# manter:
# - todas as linhas com CRD != 0
# - apenas a primeira linha com CRD == 0
BDOSS = BDOSS[(BDOSS['CRD'] != 0) | (zero_count == 1)].copy()

In [116]:
BDOSS[BDOSS['CONTRIB']=='0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5']

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,MENSALIDADE_CORR,CRD,SREC,ACTIVIDADE_GLOBAL,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO
1044465,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2024-10-31,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,0,56,3000.0,3000.0,110.832043,NaN,3520.981,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1158889,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2024-11-30,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,0,56,3000.0,3000.0,110.832043,NaN,3520.981,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1273314,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2024-12-31,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,1,56,3000.0,3000.0,110.832043,NaN,3434.892,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1387257,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2025-01-31,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,2,56,3000.0,3000.0,110.832043,NaN,3348.140,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
1497668,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,SAN,2025-02-28,2024-11-12,2024-11-18,2024-11-18,2025-02-10,36,2,56,3000.0,3000.0,110.832043,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W
6,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,ENC,2024-01-31,2019-06-14,2019-06-28,2019-06-28,2019-06-28,72,55,55,5000.0,5000.0,102.689443,NaN,1652.349,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W
112231,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,SAN,2024-02-29,2019-06-14,2019-06-28,2019-06-28,2024-02-07,72,55,55,5000.0,5000.0,102.689443,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W
2179819,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-08-31,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,0,56,10500.0,10500.0,165.682282,NaN,12636.101,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W
2297362,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-09-30,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,1,56,10500.0,10500.0,165.682282,NaN,12566.088,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W
2416440,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-10-31,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,2,56,10500.0,10500.0,165.682282,NaN,12495.616,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W
2537003,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-11-30,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,3,56,10500.0,10500.0,148.056088,NaN,12424.673,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W

In [117]:
BDOSS['DIF_CRD_NEXT'] = BDOSS['CRD'] - (BDOSS.groupby(['CONTRIB', 'DOSSIER'])['CRD'].shift(-1))
col = BDOSS.pop('DIF_CRD_NEXT')
BDOSS.insert(19, 'DIF_CRD_NEXT', col)
BDOSS.head()

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,MENSALIDADE_CORR,DIF_CRD_NEXT,CRD,SREC,ACTIVIDADE_GLOBAL,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO
576857,00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ffb8db787131bb069c76,P,CL,EP,0,ENC,2024-06-30,2024-06-25,2024-06-27,2024-06-27,2024-06-27,84,0,19,8000.0,8000.0,158.359889,NaN,77.933,9575.287,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1278.521,74.0,2020.0,P,8600,0.0,W
694260,00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ffb8db787131bb069c76,P,CL,EP,0,ENC,2024-07-31,2024-06-25,2024-06-27,2024-06-27,2024-06-27,84,1,19,8000.0,8000.0,158.359889,NaN,78.628,9497.354,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1278.521,74.0,2020.0,P,8600,0.0,W
812122,00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ffb8db787131bb069c76,P,CL,EP,0,ENC,2024-08-31,2024-06-25,2024-06-27,2024-06-27,2024-06-27,84,2,19,8000.0,8000.0,158.359889,NaN,9418.726,9418.726,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1513.466,80.0,2024.0,P,8600,0.0,W
930223,00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ffb8db787131bb069c76,P,CL,EP,0,SAN,2024-09-30,2024-06-25,2024-06-27,2024-06-27,2024-10-03,84,3,19,8000.0,8000.0,158.359889,NaN,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1513.466,80.0,2024.0,P,8600,0.0,W
930224,00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,a34f4d89a43b924b483dc829a65ccba8b0f90e0afc206396405115a02cd513fc,P,CL,EP,0,ENC,2024-09-30,2024-09-13,2024-09-30,2024-09-30,2024-09-30,120,1,19,16000.0,16000.0,280.401466,NaN,82.508,19336.270,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1513.466,80.0,2024.0,P,8600,0.0,W

**- DELAY (amount of time, in months, that the client delayed payments)**

Corrigi esta variavel

In [118]:
#BDOSS['DELAY'] = BDOSS['RANGCLI'] - BDOSS['RANGPRO']
conditions = [
    BDOSS['DIF_CRD_NEXT'] == 0.00,                   # não pagou
    BDOSS['DIF_CRD_NEXT'] > BDOSS['MENSALIDADE'],   # pagou mais
    BDOSS['DIF_CRD_NEXT'] < BDOSS['MENSALIDADE']   # pagou normal
]

choices = [-1, 1, 0]

BDOSS['DELAY'] = np.select(conditions, choices, default=0)

In [119]:
BDOSS[BDOSS['CONTRIB']=='0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297']

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,MENSALIDADE_CORR,DIF_CRD_NEXT,CRD,SREC,ACTIVIDADE_GLOBAL,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO,DELAY
0,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-01-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,69,69,20000.0,20000.0,347.44728,NaN,212.620,13208.455,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
112225,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-02-29,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,70,70,20000.0,20000.0,347.44728,NaN,214.344,12995.835,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
226251,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-03-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,71,71,20000.0,20000.0,347.44728,NaN,216.078,12781.491,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
342742,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-04-30,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,72,72,20000.0,20000.0,347.44728,NaN,217.822,12565.413,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
459532,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-05-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,73,73,20000.0,20000.0,347.44728,NaN,219.573,12347.591,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
576858,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-06-30,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,74,74,20000.0,20000.0,347.44728,NaN,221.335,12128.018,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
694261,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-07-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,75,75,20000.0,20000.0,347.44728,NaN,223.117,11906.683,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
812123,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-08-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,76,76,20000.0,20000.0,347.44728,NaN,451.627,11683.566,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,1
930225,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-09-30,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,78,78,20000.0,20000.0,347.44728,NaN,228.528,11231.939,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
1044459,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-10-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,79,79,20000.0,20000.0,347.44728,NaN,0.000,11003.411,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,-1
1158883,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-11-30,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,79,79,20000.0,20000.0,347.44728,NaN,230.355,11003.411,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
1273307,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2024-12-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,80,80,20000.0,20000.0,347.44728,NaN,232.192,10773.056,347.447,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
1387252,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-01-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,81,81,20000.0,20000.0,347.44728,NaN,234.047,10540.864,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
1497663,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-02-28,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,82,82,20000.0,20000.0,347.44728,NaN,235.911,10306.817,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
1608536,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-03-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,83,83,20000.0,20000.0,347.44728,NaN,237.782,10070.906,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
1720699,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-04-30,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,84,84,20000.0,20000.0,347.44728,NaN,239.671,9833.124,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
1833525,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-05-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,85,85,20000.0,20000.0,347.44728,NaN,241.567,9593.453,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
1947919,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-06-30,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,86,86,20000.0,20000.0,347.44728,NaN,243.469,9351.886,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
2063124,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-07-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,87,87,20000.0,20000.0,347.44728,NaN,245.390,9108.417,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
2179814,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-08-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,88,88,20000.0,20000.0,347.44728,NaN,247.316,8863.027,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
2297357,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-09-30,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,89,89,20000.0,20000.0,347.44728,NaN,249.258,8615.711,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
2416435,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-10-31,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,90,90,20000.0,20000.0,347.44728,NaN,251.206,8366.453,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0
2536998,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,P,CL,EP,0,ENC,2025-11-30,2018-03-29,2018-04-16,2018-04-16,2018-04-16,120,91,91,20000.0,20000.0,347.44728,NaN,NaN,8115.247,0.000,NaN,0.0,0.0,000000000000000000000000,0,120.0,P,1113.258,80.0,1988.0,P,2845,1.0,A,0

Criação da varialvel temporal para o survival methods

In [120]:
# ordenar
BDOSS = BDOSS.sort_values(['CONTRIB', 'DOSSIER', 'OBS_DATE']).copy()

# última OBS_DATE de cada dossier, replicada em todas as linhas do grupo
BDOSS['LAST_OBS_DATE'] = BDOSS.groupby(['CONTRIB', 'DOSSIER'])['OBS_DATE'].transform('max')

# tempo em meses inteiros
BDOSS['TIME_MONTHS'] = (
    (BDOSS['LAST_OBS_DATE'].dt.year - BDOSS['DCREAT'].dt.year) * 12
    + (BDOSS['LAST_OBS_DATE'].dt.month - BDOSS['DCREAT'].dt.month)
)

In [121]:
BDOSS[BDOSS['CONTRIB']=='0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5']

,CONTRIB,DOSSIER,POLE,TYPEPROD,PRODALP,BICONTRATO,POS,OBS_DATE,DCREAT,DATFIN,D1FIN,DPOS,DURDEG,RANGPRO,RANGCLI,MTFINO,MTFIN,MENSALIDADE,MENSALIDADE_CORR,DIF_CRD_NEXT,CRD,SREC,ACTIVIDADE_GLOBAL,RN,RD,RISK,RISKA,AGFIN,PAGAMENTO,RESSO,CSP,DCSP,NATIO,PTT,NBENF,MODCONTACTO,DELAY,LAST_OBS_DATE,TIME_MONTHS
1044465,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2024-10-31,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,0,56,3000.0,3000.0,110.832043,NaN,0.000,3520.981,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W,-1,2025-02-28,3
1158889,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2024-11-30,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,0,56,3000.0,3000.0,110.832043,NaN,86.089,3520.981,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W,0,2025-02-28,3
1273314,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2024-12-31,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,1,56,3000.0,3000.0,110.832043,NaN,86.752,3434.892,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W,0,2025-02-28,3
1387257,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,ENC,2025-01-31,2024-11-12,2024-11-18,2024-11-18,2024-11-18,36,2,56,3000.0,3000.0,110.832043,NaN,3348.140,3348.140,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W,1,2025-02-28,3
1497668,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,9df63a4290dd28c6b6ebd8d95ad0f03820fb9b5bc14542b37fa75118a47873bd,P,CL,EP,0,SAN,2025-02-28,2024-11-12,2024-11-18,2024-11-18,2025-02-10,36,2,56,3000.0,3000.0,110.832043,NaN,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2959.138,35.0,1995.0,P,4580,2.0,W,0,2025-02-28,3
6,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,ENC,2024-01-31,2019-06-14,2019-06-28,2019-06-28,2019-06-28,72,55,55,5000.0,5000.0,102.689443,NaN,1652.349,1652.349,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W,1,2024-02-29,56
112231,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,e23f2618173f6215644610542a97a3ab5b070dd7dfe75e776c4b7738ee712c38,P,CL,EP,0,SAN,2024-02-29,2019-06-14,2019-06-28,2019-06-28,2024-02-07,72,55,55,5000.0,5000.0,102.689443,NaN,NaN,0.000,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,1788.652,35.0,1995.0,P,4425,2.0,W,0,2024-02-29,56
2179819,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-08-31,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,0,56,10500.0,10500.0,165.682282,NaN,70.013,12636.101,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W,0,2025-11-30,3
2297362,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-09-30,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,1,56,10500.0,10500.0,165.682282,NaN,70.472,12566.088,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W,0,2025-11-30,3
2416440,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-10-31,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,2,56,10500.0,10500.0,165.682282,NaN,70.943,12495.616,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W,0,2025-11-30,3
2537003,0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5,f85b35e4fd8f7db5b374fd07b8cc4a14d8273801c04ac4334e571673b27e42ce,P,CL,EP,0,ENC,2025-11-30,2025-08-14,2025-08-29,2025-08-29,2025-08-29,120,3,56,10500.0,10500.0,148.056088,NaN,NaN,12424.673,0.0,NaN,0.0,0.0,000000000000000000000000,0,118.0,P,2628.931,35.0,1995.0,P,4580,0.0,W,0,2025-11-30,3

**Data Agregation**

We will start by agregating every DOSSIER per client.

In [122]:
def moda(series):
    m = series.mode()
    return m.iloc[0] if not m.empty else np.nan

In [123]:
agg_dossier = (BDOSS.groupby(['CONTRIB', 'DOSSIER']).agg(
    #counting every 'POS' result
    sol_count = ('POS', lambda x: (x == 'SOL').sum()),
    san_count = ('POS', lambda x: (x == 'SAN').sum()),
    enc_count = ('POS', lambda x: (x == 'ENC').sum()),
    rbt_count = ('POS', lambda x: (x == 'RBT').sum()),
    
    #DURDEG, MTFINO and MENSALIDADE are constant in the dossier
    #RANGPRO, RANGCLI e HISTORIAL - max
    #CRD - min 
    #RESSO AND NBENF - mean
    #AGFIN, PAGAMENTO, CSP, NATIO, PTT and MODCONTACTO - mode
    #faltam: POLE, PRODALP, RN, DATAS IMPORTANTES, SHREK
    
    DCREAT = ('DCREAT', 'first'),
    DCRD_0 = ('OBS_DATE', lambda x: x[BDOSS.loc[x.index, 'CRD'] == 0].min()),
    CLOSE_DATE = ('OBS_DATE', lambda x: x[BDOSS.loc[x.index, 'POS'].isin(['SAN','SOL'])].min()),
    TIME_MONTHS = ('TIME_MONTHS', 'first'),
    DURDEG = ('DURDEG', 'first'),
    RANGPRO_max = ('RANGPRO', 'max'),
    RANGCLI_max = ('RANGCLI', 'max'),
    delay_mean = ('DELAY', 'sum'),
    delay_max = ('DELAY', 'max'),
    
    MENSALIDADE = ('MENSALIDADE', 'first'),     
    CRD_min = ('CRD', 'min'),
    MTFINO = ('MTFINO', 'first'),
    RESSO_mean = ('RESSO', 'mean'),
    RISKA_mean = ('RISKA', 'mean'),
    NBENF_mean = ('NBENF', 'mean'),
    RN_mean = ('RN', 'mean'),
    SREC = ('SREC', 'mean'),

    POLE = ('POLE', moda),
    PRODALP = ('PRODALP', moda),
    AGFIN = ('AGFIN', moda),
    PAGAMENTO = ('PAGAMENTO', moda),
    CSP = ('CSP', moda),
    NATIO = ('NATIO', moda),
    PTT = ('PTT', moda),
    MODCONTACTO = ('MODCONTACTO', moda),
).reset_index())

In [124]:
dup_check = BDOSS.groupby('CONTRIB')['DOSSIER'].nunique()
dup_check[dup_check > 1]

CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981    2
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a    2
0005f134494d2ab97ed5d4164994dcde766a3f77cdb3a915e0cf605c564e7aa5    3
0009a4ece0de73966d685771c1214af5685439e15380e06dc53b6ddde368ac37    2
0009db955d6a7fee16f7aa74c6633d71b04474c4957bc3b4577c2bc279577b0e    2
                                                                   ..
fff6e0cd9eda17c7d24f57e3ca7e82c1df3fc4c0340d4acc27a21a7b8fd22b26    2
fff9d6d8fa1e236901f5dfd67c755b924aa7fa975250114d4aab9b1f09f9236a    2
fffbc66ca4256976c9932916770f1ff3b23aacce5998ffc7d570a73378d619df    2
fffbfb06fdb05fb48a739b0a23650122a66ff61669a5b3e34d22144d0f0c2049    2
fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67dc5b24a0b5f3260e7    2
Name: DOSSIER, Length: 27706, dtype: int64

After this first agregation we can see that 8 dossiers appear twice on our agg_dossier DataFrame.

We determined that the reason is for the clients to be married and share the dossiers.

In [125]:
def next_valid_dossier(group):
    group = group.copy()

    next_dates = []
    dcreat = group['DCREAT'].values
    close = group['CLOSE_DATE'].values

    for i in range(len(group)):
        if pd.isna(close[i]):   
            next_dates.append(pd.NaT)
            continue

        future_loans = dcreat[dcreat > close[i]]

        if len(future_loans) > 0:
            next_dates.append(future_loans.min())
        else:
            next_dates.append(pd.NaT)

    group['NEXT_DOSSIER_DATE'] = next_dates

    return group

In [126]:
agg_dossier = (agg_dossier.groupby('CONTRIB', group_keys=False).apply(next_valid_dossier))

C:\Users\alano\AppData\Local\Temp\ipykernel_10524\3644291354.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  agg_dossier = (agg_dossier.groupby('CONTRIB', group_keys=False).apply(next_valid_dossier))

In [127]:
agg_dossier['DAYS_TO_NEXT'] = (agg_dossier['NEXT_DOSSIER_DATE'] - agg_dossier['CLOSE_DATE']).dt.days

agg_dossier['CHURN'] = None

closed = agg_dossier['CLOSE_DATE'].notna()

agg_dossier.loc[closed, 'CHURN'] = (
    (agg_dossier.loc[closed, 'DAYS_TO_NEXT'] > 30) |
    (agg_dossier.loc[closed, 'DAYS_TO_NEXT'].isna()))

In [128]:
agg_dossier#[agg_dossier['CONTRIB'] == '00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981']#.iloc[0, 1]#['DAYS_TO_NEXT'].sort_values(ascending = False)

,CONTRIB,DOSSIER,sol_count,san_count,enc_count,rbt_count,DCREAT,DCRD_0,CLOSE_DATE,TIME_MONTHS,DURDEG,RANGPRO_max,RANGCLI_max,delay_mean,delay_max,MENSALIDADE,CRD_min,MTFINO,RESSO_mean,RISKA_mean,NBENF_mean,RN_mean,SREC,POLE,PRODALP,AGFIN,PAGAMENTO,CSP,NATIO,PTT,MODCONTACTO,NEXT_DOSSIER_DATE,DAYS_TO_NEXT,CHURN
0,00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ffb8db787131bb069c76,0,1,3,0,2024-06-25,2024-09-30,2024-09-30,3,84,3,19,1,1,158.359889,0.000,8000.00,1395.993500,0.0,0.0,0.0,0.000000,P,EP,118.0,P,74.0,P,8600,W,NaT,NaN,True
1,00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,a34f4d89a43b924b483dc829a65ccba8b0f90e0afc206396405115a02cd513fc,0,1,8,0,2024-09-13,2025-11-30,2025-11-30,14,120,13,19,1,1,280.401466,0.000,16000.00,1513.466000,0.0,0.0,0.0,0.000000,P,EP,118.0,P,80.0,P,8600,W,NaT,NaN,True
2,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,0,0,23,0,2018-03-29,NaT,NaT,92,120,91,91,0,1,347.447280,8115.247,20000.00,1113.258000,0.0,1.0,0.0,15.106391,P,EP,120.0,P,80.0,P,2845,A,NaT,NaN,None
3,0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a,1c848abbdf2867f690d6c07cd30f110a0b49fcd44b7202d95cfd8ba504a84f6c,1,0,0,0,2001-09-27,2024-03-31,2024-03-31,270,60,21,21,0,0,184.214593,0.000,5985.57,678.483000,0.0,2.0,1.0,0.000000,P,EP,117.0,P,60.0,P,2745,T,NaT,NaN,True
4,0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a,796b87efb05b1ec3f822189b7b5fe25be06390e7462d228bc34ef083de72f011,1,0,0,0,2001-09-21,2024-03-31,2024-03-31,270,60,21,21,0,0,424.699203,0.000,13467.54,678.483000,0.0,2.0,1.0,0.000000,P,EP,117.0,P,60.0,P,2745,T,NaT,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185595,fffc991d73df732084dab58938d520b8a5d8712474fa53902c42190d5b1e0f9b,8a1945dd1c8ef5d381bef27f69ef52bd6b19729822aea71582af5034c1e9a250,1,0,0,0,2021-02-12,2024-01-31,2024-01-31,35,34,34,34,0,0,57.095138,0.000,1500.00,896.196000,0.0,1.0,0.0,0.000000,P,EP,118.0,P,80.0,P,4400,W,NaT,NaN,True
185596,fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9adcf1007f61b9a9c4,b6e4983596a5a38f9bfd54da8bff33bcae0bfc46138f9a560bffe046f78cf800,0,0,23,0,2021-06-17,NaT,NaT,53,60,53,53,0,1,416.654611,2563.528,15000.00,1623.880000,0.0,0.0,0.0,0.000000,P,EP,120.0,P,80.0,P,9560,W,NaT,NaN,None
185597,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c5ce4e07c92bfe1f3b,5f58cce05624b68e1c810c7eddea58a455e4e519b1d56a83d25691d13a2764e4,0,1,2,0,2022-03-24,2024-03-31,2024-03-31,24,84,23,34,1,1,267.471639,0.000,12000.00,955.766667,0.333333,0.0,0.0,233.510333,P,EPF,117.0,P,80.0,P,2845,A,NaT,NaN,True
185598,ffff943c736f98d4840f65328ba372a29689312dd781b437624e6112d3d6803b,028095f193e6a9ceaf6878e2f08ea30b2218d02b27d23daaf486a33636e4b637,0,0,1,0,2023-10-23,NaT,NaT,3,24,3,6,0,0,135.336545,2572.760,2500.00,924.580000,1.0,0.0,1.0,0.000000,P,EP,119.0,P,60.0,P,2825,A,NaT,NaN,None
185599,ffffe82f7c91df4a087341fe89db094be2a89294f2178572b937a270b0c9f669,159941797f0c7dd45dcb8638c273da1614078db068e3300c99b74aadc169f45f,0,1,0,0,2021-02-10,2024-01-31,2024-01-31,35,84,32,87,0,0,415.242666,0.000,20000.00,2234.521000,0.0,1.0,0.0,0.000000,P,EPF,117.0,P,60.0,P,2730,A,NaT,NaN,True

In [129]:
agg_dossier['CHURN'].unique()

array([True, None, False], dtype=object)

In [130]:
agg_dossier[agg_dossier['CHURN'] == True]

,CONTRIB,DOSSIER,sol_count,san_count,enc_count,rbt_count,DCREAT,DCRD_0,CLOSE_DATE,TIME_MONTHS,DURDEG,RANGPRO_max,RANGCLI_max,delay_mean,delay_max,MENSALIDADE,CRD_min,MTFINO,RESSO_mean,RISKA_mean,NBENF_mean,RN_mean,SREC,POLE,PRODALP,AGFIN,PAGAMENTO,CSP,NATIO,PTT,MODCONTACTO,NEXT_DOSSIER_DATE,DAYS_TO_NEXT,CHURN
0,00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ffb8db787131bb069c76,0,1,3,0,2024-06-25,2024-09-30,2024-09-30,3,84,3,19,1,1,158.359889,0.0,8000.00,1395.993500,0.0,0.0,0.0,0.000000,P,EP,118.0,P,74.0,P,8600,W,NaT,NaN,True
1,00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,a34f4d89a43b924b483dc829a65ccba8b0f90e0afc206396405115a02cd513fc,0,1,8,0,2024-09-13,2025-11-30,2025-11-30,14,120,13,19,1,1,280.401466,0.0,16000.00,1513.466000,0.0,0.0,0.0,0.000000,P,EP,118.0,P,80.0,P,8600,W,NaT,NaN,True
3,0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a,1c848abbdf2867f690d6c07cd30f110a0b49fcd44b7202d95cfd8ba504a84f6c,1,0,0,0,2001-09-27,2024-03-31,2024-03-31,270,60,21,21,0,0,184.214593,0.0,5985.57,678.483000,0.0,2.0,1.0,0.000000,P,EP,117.0,P,60.0,P,2745,T,NaT,NaN,True
4,0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a,796b87efb05b1ec3f822189b7b5fe25be06390e7462d228bc34ef083de72f011,1,0,0,0,2001-09-21,2024-03-31,2024-03-31,270,60,21,21,0,0,424.699203,0.0,13467.54,678.483000,0.0,2.0,1.0,0.000000,P,EP,117.0,P,60.0,P,2745,T,NaT,NaN,True
5,0000e359b15a80ba12c7f60c0fe06ffc68621c87f13a4f88f54188543d9a09c8,b83e6ef0c9c12f8304d86c40458a5b88ec72e534201c32a1a99618e5be83ced1,0,1,0,0,2019-01-28,2024-01-31,2024-01-31,60,72,34,34,0,0,56.017772,0.0,2500.00,838.186000,0.0,0.0,1.0,0.000000,P,EP,120.0,N,91.0,P,2855,A,NaT,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185593,fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67dc5b24a0b5f3260e7,44646b249bca38e9954ca24c81aa0dd55c1f286a257394bc28f2672d2e895ff0,1,0,8,0,2022-09-27,2024-09-30,2024-09-30,24,24,24,61,0,0,268.768666,0.0,5000.00,1346.169444,0.0,3.0,0.0,0.000000,P,EP,117.0,P,91.0,P,9500,A,NaT,NaN,True
185594,fffc6e5b2f4865ed2d2c6c8724f9c4c340e47d2b052bc67dc5b24a0b5f3260e7,78350b49408237d9be0249768a20c97f5b40f8260b0a4632d120c4f4db1d2b68,0,1,9,0,2021-10-26,2024-10-31,2024-10-31,36,84,36,61,2,1,51.206134,0.0,3000.00,1347.630800,0.1,3.0,0.0,0.000000,P,EP,119.0,P,91.0,P,9500,A,NaT,NaN,True
185595,fffc991d73df732084dab58938d520b8a5d8712474fa53902c42190d5b1e0f9b,8a1945dd1c8ef5d381bef27f69ef52bd6b19729822aea71582af5034c1e9a250,1,0,0,0,2021-02-12,2024-01-31,2024-01-31,35,34,34,34,0,0,57.095138,0.0,1500.00,896.196000,0.0,1.0,0.0,0.000000,P,EP,118.0,P,80.0,P,4400,W,NaT,NaN,True
185597,fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c5ce4e07c92bfe1f3b,5f58cce05624b68e1c810c7eddea58a455e4e519b1d56a83d25691d13a2764e4,0,1,2,0,2022-03-24,2024-03-31,2024-03-31,24,84,23,34,1,1,267.471639,0.0,12000.00,955.766667,0.333333,0.0,0.0,233.510333,P,EPF,117.0,P,80.0,P,2845,A,NaT,NaN,True
185599,ffffe82f7c91df4a087341fe89db094be2a89294f2178572b937a270b0c9f669,159941797f0c7dd45dcb8638c273da1614078db068e3300c99b74aadc169f45f,0,1,0,0,2021-02-10,2024-01-31,2024-01-31,35,84,32,87,0,0,415.242666,0.0,20000.00,2234.521000,0.0,1.0,0.0,0.000000,P,EPF,117.0,P,60.0,P,2730,A,NaT,NaN,True

In [131]:
agg_dossier[agg_dossier['CHURN'] == False]

,CONTRIB,DOSSIER,sol_count,san_count,enc_count,rbt_count,DCREAT,DCRD_0,CLOSE_DATE,TIME_MONTHS,DURDEG,RANGPRO_max,RANGCLI_max,delay_mean,delay_max,MENSALIDADE,CRD_min,MTFINO,RESSO_mean,RISKA_mean,NBENF_mean,RN_mean,SREC,POLE,PRODALP,AGFIN,PAGAMENTO,CSP,NATIO,PTT,MODCONTACTO,NEXT_DOSSIER_DATE,DAYS_TO_NEXT,CHURN
86,001e15da6f3ead7dfbfd602d687d2efebbe7fbb541487de11529f347e29a13ad,555cf446e94b979ad57b249878b5f6b9f5719f65d9e7d273b68fea5593d48627,0,1,9,0,2022-03-14,2024-10-31,2024-10-31,31,60,33,33,2,1,457.819975,0.0,18000.00,2620.4840,0.0,0.0,0.0,0.000000,P,EP,120.0,P,35.0,P,4400,W,2024-11-25,25.0,False
185,004063d402b0a89ff04889fec8f59d5b05e3f71878d9ca44f8b8568429bfb0ee,c575fae241b37687a11ca7c767b7f79eecd762b1faa3c44c3aefd4faea099520,1,0,12,0,2024-03-18,2025-03-31,2025-03-31,12,12,12,25,0,1,261.849278,0.0,2535.23,1437.7350,0.0,1.0,0.0,0.000000,P,EPF,117.0,P,80.0,P,4760,A,2025-04-15,15.0,False
280,00628bbe8cb9cbafba392423d2e0c4b4378f557f0e6a01773b7b5be090e70f1c,a14917cea99d772c2f161dfab106f1e1193a77479efca45e8aa05e05bb92c986,0,1,4,0,2025-02-24,2025-06-30,2025-06-30,4,24,3,7,1,1,230.496307,0.0,4000.00,0.0000,0.0,1.0,0.0,0.000000,P,EP,118.0,P,80.0,P,2660,W,2025-07-23,23.0,False
406,00936059df64b49f9795325b9c49e6c546355810872b885ce3db10c697148cb0,e9518e43d3fee655be35077960be90ec640dae27b1123703a726264ccfddcd6e,0,1,4,0,2024-05-26,2024-10-31,2024-10-31,5,84,5,5,1,1,151.571891,0.0,7000.00,998.9712,0.0,2.0,0.0,0.000000,P,EP,120.0,P,80.0,P,7400,W,2024-11-14,14.0,False
735,01034a0ae160ab703f17e47597f59f64207054807b4878f9b09eb26b26e0ac51,807de7dc60132b63d723e81ef097dc11b78c7baa58531c54fc013ca1297bfa43,0,1,0,0,2023-02-20,2024-01-31,2024-01-31,11,60,7,7,0,0,58.776080,0.0,2500.00,1156.8770,0.0,0.0,0.0,0.000000,P,EP,117.0,P,31.0,P,2700,A,2024-02-27,27.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185051,ff40b8018a2a7ec6024d7a6e03eed1c1a7f0bdf47c9d782e28c1207c6719ed23,0cfde82b80ae235e3a9428645f86bbbb86f566ff4a1a793aec6f87ee94d821c2,0,1,4,0,2023-07-11,2024-05-31,2024-05-31,10,18,11,13,1,1,71.396290,0.0,1000.00,1216.9580,0.0,0.0,0.0,42.837600,P,EP,118.0,P,80.0,P,2700,W,2024-06-28,28.0,False
185054,ff40b8018a2a7ec6024d7a6e03eed1c1a7f0bdf47c9d782e28c1207c6719ed23,e0395449258f36b433cddfb12df5ce07ea38753712c6f51d1864a376fe93d426,0,1,4,0,2023-08-29,2024-05-31,2024-05-31,9,36,9,13,1,1,204.316588,0.0,5000.00,1216.9580,0.0,0.0,0.0,122.590200,P,EP,118.0,P,80.0,P,2700,W,2024-06-28,28.0,False
185124,ff5404a527b3a43769ba7c79a95e2509a358f799c927baaa864e6ce5bb2c05fd,9973f1a8879a4aa8c503bb4bba9b8f32430fa5313bcd65bb02eef8bca17f0968,1,0,11,0,2022-12-21,2024-12-31,2024-12-31,24,24,24,68,0,1,521.918630,0.0,10000.00,5797.0250,0.0,0.0,0.0,0.000000,P,EPF,117.0,P,56.0,P,2790,A,2025-01-22,22.0,False
185287,ff902ac49d40578176ac77da15a10f7f5e292143db20ba948c206245e1d61599,d402fa3d5b3df6c5db63c410009029adf438fc532bc6a1cfeabdddbfe41be37b,1,0,12,0,2024-11-04,2025-10-31,2025-10-31,11,12,12,17,-1,0,213.931990,0.0,2000.00,2289.1110,0.0,0.0,0.0,50.060462,P,EP,117.0,P,60.0,P,4745,A,2025-11-07,7.0,False
185391,ffba555bd3212c172bd0f75d1eb4135769e6f34ccc3424940222de04e78364b2,a598a12c31f2cfa8893ee6bda1375bc79b069dcf1f21c30abf64cf6474bab314,0,1,5,0,2023-07-28,2024-06-30,2024-06-30,11,84,11,121,1,1,102.677655,0.0,8000.00,2075.2480,0.0,1.0,0.0,0.000000,P,EP,120.0,P,31.0,P,2650,W,2024-07-02,2.0,False

In [132]:
agg_dossier[agg_dossier['CHURN'].isna()]

,CONTRIB,DOSSIER,sol_count,san_count,enc_count,rbt_count,DCREAT,DCRD_0,CLOSE_DATE,TIME_MONTHS,DURDEG,RANGPRO_max,RANGCLI_max,delay_mean,delay_max,MENSALIDADE,CRD_min,MTFINO,RESSO_mean,RISKA_mean,NBENF_mean,RN_mean,SREC,POLE,PRODALP,AGFIN,PAGAMENTO,CSP,NATIO,PTT,MODCONTACTO,NEXT_DOSSIER_DATE,DAYS_TO_NEXT,CHURN
2,0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,0,0,23,0,2018-03-29,NaT,NaT,92,120,91,91,0,1,347.447280,8115.247,20000.0,1113.258,0.0,1.0,0.000000,15.106391,P,EP,120.0,P,80.0,P,2845,A,NaT,NaN,None
6,0000f858346061c53064586a3347b34659565a6712d004e64309c2473f76faed,29c3cfb34c4e2ecd6749b0c1a6205dfce33c0e717514560542d65af5e63e2157,0,0,23,0,2019-09-23,NaT,NaT,74,84,74,74,0,1,100.073575,883.500,5000.0,1314.144,0.0,2.0,0.000000,0.000000,P,EP,118.0,P,80.0,P,2635,W,NaT,NaN,None
7,00025459b703e1c308553e83a6d545a71fe6a787c2dd1c62d26faa0207cc5b08,446d96905d26356fb4f1d3e1e6da3868b8106b09a558e61d70dcb3944412ecac,0,0,23,0,2023-01-09,NaT,NaT,34,60,35,37,0,1,162.097525,3419.266,6000.0,1031.650,0.0,0.0,0.000000,0.000000,P,EPF,117.0,P,80.0,P,5090,A,NaT,NaN,None
9,00041ebafb1270a818c30cb1fb20d3699002196644ea8fd9df9425df6f49db00,26d59ea8a93be739e9fc4a0404f07c73aae276243e5cd6236580eb19aa138a56,0,0,10,0,2021-02-10,NaT,NaT,46,84,43,43,2,1,463.755537,14665.602,20500.0,1113.258,0.3,0.0,1.900000,-46.375600,N,EXT,119.0,P,80.0,P,2835,A,NaT,NaN,None
11,00050fe9f0e69ce221a574af0baaff0b37c598af7a5cc6eb42a2afd52d4e0d4a,cd128e1f3c6d6bc9dd2414eeb60f44241977a35fd94885881bfec649d1b8bace,0,0,23,0,2023-09-11,NaT,NaT,26,48,27,121,0,1,131.155715,2349.858,4080.0,877.293,0.0,1.0,0.000000,0.000000,P,EP,117.0,P,80.0,P,4475,A,NaT,NaN,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
185588,fffbc66ca4256976c9932916770f1ff3b23aacce5998ffc7d570a73378d619df,dea39098d015a030ea0b3ead87c82ccca9137f784f86c7a4e15a2b1365e14fd8,0,0,22,0,2018-12-21,NaT,NaT,83,84,83,83,1,1,157.667572,137.403,7430.0,977.381,0.0,1.0,0.045455,-7.166727,P,EPF,118.0,P,31.0,P,4820,W,NaT,NaN,None
185590,fffbfb06fdb05fb48a739b0a23650122a66ff61669a5b3e34d22144d0f0c2049,ac0c808a63bb91659f6f5af780a60c1de56b705618be2abd5f6596eaaeafb206,0,0,9,0,2025-03-03,NaT,NaT,8,120,9,49,0,0,251.897648,17422.059,15000.0,0.000,0.0,0.0,0.000000,0.000000,P,EP,118.0,P,55.0,P,2745,W,NaT,NaN,None
185591,fffc47b191b25cbc3dbc9ce436b94e52d2084144ee5bec31fd2457f3cff87c3c,43fefbb99328741294aa67fa5bb29cdaf0acff276e282dcfdd480b63fd6b0eb2,0,0,7,0,2025-05-29,NaT,NaT,6,36,6,6,0,0,81.856368,1994.881,2000.0,0.000,0.142857,2.0,0.000000,1.923143,P,EP,120.0,P,80.0,P,4485,W,NaT,NaN,None
185596,fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9adcf1007f61b9a9c4,b6e4983596a5a38f9bfd54da8bff33bcae0bfc46138f9a560bffe046f78cf800,0,0,23,0,2021-06-17,NaT,NaT,53,60,53,53,0,1,416.654611,2563.528,15000.0,1623.880,0.0,0.0,0.000000,0.000000,P,EP,120.0,P,80.0,P,9560,W,NaT,NaN,None
185598,ffff943c736f98d4840f65328ba372a29689312dd781b437624e6112d3d6803b,028095f193e6a9ceaf6878e2f08ea30b2218d02b27d23daaf486a33636e4b637,0,0,1,0,2023-10-23,NaT,NaT,3,24,3,6,0,0,135.336545,2572.760,2500.0,924.580,1.0,0.0,1.000000,0.000000,P,EP,119.0,P,60.0,P,2825,A,NaT,NaN,None

In [133]:
print(agg_dossier[agg_dossier['CHURN'].isna()]['sol_count'].sum(), agg_dossier[agg_dossier['CHURN'].isna()]['san_count'].sum())

0 0

In [134]:
agg_dossier[(agg_dossier['sol_count'] > 0) & (agg_dossier['san_count'] > 0)]

Empty DataFrame
Columns: [CONTRIB, DOSSIER, sol_count, san_count, enc_count, rbt_count, DCREAT, DCRD_0, CLOSE_DATE, TIME_MONTHS, DURDEG, RANGPRO_max, RANGCLI_max, delay_mean, delay_max, MENSALIDADE, CRD_min, MTFINO, RESSO_mean, RISKA_mean, NBENF_mean, RN_mean, SREC, POLE, PRODALP, AGFIN, PAGAMENTO, CSP, NATIO, PTT, MODCONTACTO, NEXT_DOSSIER_DATE, DAYS_TO_NEXT, CHURN]
Index: []

In [135]:
#agg_dossier.drop('CHURN', axis = 1, inplace = True)
agg_dossier.drop('NEXT_DOSSIER_DATE', axis = 1, inplace = True)
#agg_dossier.drop('next_dossier_date', axis = 1, inplace = True)
agg_dossier.drop('DAYS_TO_NEXT', axis = 1, inplace = True)
agg_dossier.drop('DCRD_0', axis = 1, inplace = True)
agg_dossier.drop('CLOSE_DATE', axis = 1, inplace = True)

## MERGE

In [151]:
BNP = (
    agg_dossier
    .merge(CRC_agg, on='CONTRIB', how='left')
    .merge(CREDSCORE, on='CONTRIB', how='left')
    .merge(FAMA, on='CONTRIB', how='left')
    .set_index('CONTRIB')
)
BNP.head()

,DOSSIER,sol_count,san_count,enc_count,rbt_count,DCREAT,TIME_MONTHS,DURDEG,RANGPRO_max,RANGCLI_max,delay_mean,delay_max,MENSALIDADE,CRD_min,MTFINO,RESSO_mean,RISKA_mean,NBENF_mean,RN_mean,SREC,POLE,PRODALP,AGFIN,PAGAMENTO,CSP,NATIO,PTT,MODCONTACTO,CHURN,count_cl_mean,count_cl_mode,count_cp_mean,count_cp_mode,count_auto_mean,count_auto_mode,count_ht_mean,count_ht_mode,count_conexo_mean,count_conexo_mode,count_other_mean,count_other_mode,montvenc_cl_mean,montvenc_cl_mode,montvenc_cp_mean,montvenc_cp_mode,montvenc_auto_mean,montvenc_auto_mode,montvenc_ht_mean,montvenc_ht_mode,montabatv_cl_mean,montabatv_cl_mode,montabatv_cp_mean,montabatv_cp_mode,montabatv_auto_mean,montabatv_auto_mode,montabatv_ht_mean,montabatv_ht_mode,balance_cl_mean,balance_cl_mode,balance_cp_mean,balance_cp_mode,balance_auto_mean,balance_auto_mode,balance_ht_mean,balance_ht_mode,dividas_cl_mean,dividas_cl_mode,dividas_cp_mean,dividas_cp_mode,dividas_auto_mean,dividas_auto_mode,dividas_ht_mean,dividas_ht_mode,sys_data_procura,kp_sqe,ks_score_tier,is_risky,Date_Obs,ALLBD_N_Dossiers__N,ALLBD_N_CL__N,ALLBD_N_CP__N,ALLBD_A_CL__N,ALLBD_A_CP__N,ALLBD_MTFINO_CL__N,ALLBD_MTFINO_CP__N,ALLBD_MTFIN_CL__N,ALLBD_MTFIN_CP__N,ALLBD_IDADE_MEAN__N,ALLBD_SUM_NUMFIN_CP__N,ALLBD_mean_active_resso__N,ALLBD_max_active_resso__N,ALLBD_mean_duration_CL__N,ALLBD_mean_lifecycle_CL__N,ALLBD_N_events__N,sdem_SITFAM,sdem_HABITAT,sdem_age,active_credit_ratio,debt_income_ratio,credit_progress,credit_remaining_ratio
CONTRIB,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,36cc29a11081476fb7fcaed11aafef6fd441c3d172f4ffb8db787131bb069c76,0,1,3,0,2024-06-25,3,84,3,19,1,1,158.359889,0.000,8000.00,1395.9935,0.0,0.0,0.0,0.000000,P,EP,118.0,P,74.0,P,8600,W,True,0.36,0,3.8,4,1.12,0,0.0,0,0.0,0,1.08,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2565.7936,0.0,1150.5924,1729.30,13479.8216,0.0,0.0,0.0,2025-02-05,H,2.0,True,2024-11-30,10.0,5.0,5.0,1.0,2.0,29720.95,3381.52,29720.95,29.5,-438.9,36.0,1142.0,1142.0,120.0,0.033333,10.0,S,F,33.0,0.272727,26.002581,0.999966,0.999966
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,a34f4d89a43b924b483dc829a65ccba8b0f90e0afc206396405115a02cd513fc,0,1,8,0,2024-09-13,14,120,13,19,1,1,280.401466,0.000,16000.00,1513.4660,0.0,0.0,0.0,0.000000,P,EP,118.0,P,80.0,P,8600,W,True,0.36,0,3.8,4,1.12,0,0.0,0,0.0,0,1.08,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2565.7936,0.0,1150.5924,1729.30,13479.8216,0.0,0.0,0.0,2025-02-05,H,2.0,True,2024-11-30,10.0,5.0,5.0,1.0,2.0,29720.95,3381.52,29720.95,29.5,-438.9,36.0,1142.0,1142.0,120.0,0.033333,10.0,S,F,33.0,0.272727,26.002581,0.999966,0.999966
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,9e4d186f6f66f2da4b816cbc6f6e05e640caf5ded07956d5fde4919118d37d43,0,0,23,0,2018-03-29,92,120,91,91,0,1,347.447280,8115.247,20000.00,1113.2580,0.0,1.0,0.0,15.106391,P,EP,120.0,P,80.0,P,2845,A,None,4.32,4,5.4,5,0.0,0,0.0,0,0.0,0,1.08,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26448.0320,26637.9,7552.1172,6746.45,0.0000,0.0,0.0,0.0,2025-04-09,D,1.0,False,2024-11-30,10.0,5.0,5.0,1.0,0.0,20000.00,0.00,20000.00,0.0,1166.9,0.0,850.0,850.0,120.0,0.675000,10.0,C,P,52.0,0.090909,23.501763,0.999950,0.999950
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a,1c848abbdf2867f690d6c07cd30f110a0b49fcd44b7202d95cfd8ba504a84f6c,1,0,0,0,2001-09-27,270,60,21,21,0,0,184.214593,0.000,5985.57,678.4830,0.0,2.0,1.0,0.000000,P,EP,117.0,P,60.0,P,2745,T,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a,796b87efb05b1ec3f822189b7b5fe25be06390e7462d228bc34ef083de72f011,1,0,0,0,2001-09-21,270,60,21,21,0,0,424.699203,0.000,13467.54,678.4830,0.0,2.0,1.0,0.000000,P,EP,117.0,P,60.0,P,2745,T,True,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## FEATURE SELCTION

In [152]:
drop_cols = [
    "DOSSIER",
    "DCREAT",
    "Date_Obs",
    "sys_data_procura"
]

df = BNP.drop(columns=drop_cols)

In [ ]:
y = df["CHURN"]
X = df.drop(columns=["CHURN"])

In [158]:
X["PTT"] = pd.to_numeric(X["PTT"], errors="coerce")

In [160]:
num_cols = X.select_dtypes(include=["int64","float64"]).columns
cat_cols = X.select_dtypes(include=["object","bool","category"]).columns

In [161]:
cardinality = X[cat_cols].nunique(dropna=False).sort_values()

low_card_cols = cardinality[cardinality <= 10].index.tolist()
high_card_cols = cardinality[cardinality > 10].index.tolist()

print("Baixa cardinalidade:", low_card_cols)
print("Alta cardinalidade:", high_card_cols)

Baixa cardinalidade: ['POLE', 'PAGAMENTO', 'is_risky', 'PRODALP', 'NATIO', 'MODCONTACTO', 'sdem_SITFAM', 'sdem_HABITAT']
Alta cardinalidade: ['kp_sqe']

In [162]:
# agrupar categorias raras nas de baixa cardinalidade
def group_rare_categories(series, min_freq=0.01):
    freq = series.value_counts(normalize=True, dropna=False)
    rare_cats = freq[freq < min_freq].index
    s = series.astype('object').copy()
    s = s.where(~s.isin(rare_cats), 'OTHER')
    return s

for col in low_card_cols:
    X[col] = group_rare_categories(X[col], min_freq=0.01)

# frequency encoding nas de alta cardinalidade
for col in high_card_cols:
    freq_map = X[col].value_counts(dropna=False, normalize=True)
    X[col + '_freq'] = X[col].map(freq_map)

# one-hot nas de baixa cardinalidade
X = pd.get_dummies(X, columns=low_card_cols, drop_first=True, dummy_na=True)

# apagar categóricas originais de alta cardinalidade
X = X.drop(columns=high_card_cols)

# limpeza final
X = X.replace([np.inf, -np.inf], np.nan)

for col in X.columns:
    if X[col].dtype == 'bool':
        X[col] = X[col].astype(int)

print("Shape final:", X.shape)
print(X.head())

Shape final: (185600, 117)
                                                                  sol_count  san_count  enc_count  rbt_count  TIME_MONTHS  DURDEG  RANGPRO_max  RANGCLI_max  delay_mean  delay_max  MENSALIDADE  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981          0          1          3          0            3      84            3           19           1          1   158.359889
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981          0          1          8          0           14     120           13           19           1          1   280.401466
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297          0          0         23          0           92     120           91           91           0          1   347.447280
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a          1          0          0          0          270      60           21           21           0          0   184.214593
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a          1          0          0          0          270      60           21           21           0          0   424.699203

                                                                   CRD_min    MTFINO  RESSO_mean  RISKA_mean  NBENF_mean  RN_mean       SREC  AGFIN   CSP   PTT  count_cl_mean  count_cl_mode  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981     0.000   8000.00   1395.9935         0.0         0.0      0.0   0.000000  118.0  74.0  8600           0.36              0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981     0.000  16000.00   1513.4660         0.0         0.0      0.0   0.000000  118.0  80.0  8600           0.36              0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297  8115.247  20000.00   1113.2580         0.0         1.0      0.0  15.106391  120.0  80.0  2845           4.32              4
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a     0.000   5985.57    678.4830         0.0         2.0      1.0   0.000000  117.0  60.0  2745           <NA>           <NA>
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a     0.000  13467.54    678.4830         0.0         2.0      1.0   0.000000  117.0  60.0  2745           <NA>           <NA>

                                                                  count_cp_mean  count_cp_mode  count_auto_mean  count_auto_mode  count_ht_mean  count_ht_mode  count_conexo_mean  count_conexo_mode  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981            3.8              4             1.12                0            0.0              0                0.0                  0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981            3.8              4             1.12                0            0.0              0                0.0                  0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297            5.4              5              0.0                0            0.0              0                0.0                  0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a           <NA>           <NA>             <NA>             <NA>           <NA>           <NA>               <NA>               <NA>
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a           <NA>           <NA>             <NA>             <NA>           <NA>           <NA>               <NA>               <NA>

                                                                  count_other_mean  count_other_mode  montvenc_cl_mean  montvenc_cl_mode  montvenc_cp_mean  montvenc_cp_mode  montvenc_auto_mean  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981              1.08                 1               0.0               0.0               0.0               0.0                 0.0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981              1.08                 1               0.0               0.0               0.0               0.0                 0.0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297              1.08                 1               0.0               0.0               0.0               0.0                 0.0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              <NA>              <NA>               NaN               NaN               NaN               NaN                 NaN
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              <NA>              <NA>               NaN               NaN               NaN               NaN                 NaN

                                                                  montvenc_auto_mode  montvenc_ht_mean  montvenc_ht_mode  montabatv_cl_mean  montabatv_cl_mode  montabatv_cp_mean  montabatv_cp_mode  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                 0.0               0.0               0.0                0.0                0.0                0.0                0.0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                 0.0               0.0               0.0                0.0                0.0                0.0                0.0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297                 0.0               0.0               0.0                0.0                0.0                0.0                0.0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                 NaN               NaN               NaN                NaN                NaN                NaN                NaN
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                 NaN               NaN               NaN                NaN                NaN                NaN                NaN

                                                                  montabatv_auto_mean  montabatv_auto_mode  montabatv_ht_mean  montabatv_ht_mode  balance_cl_mean  balance_cl_mode  balance_cp_mean  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                  0.0                  0.0                0.0                0.0              0.0              0.0              0.0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                  0.0                  0.0                0.0                0.0              0.0              0.0              0.0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297                  0.0                  0.0                0.0                0.0              0.0              0.0              0.0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                  NaN                  NaN                NaN                NaN              NaN              NaN              NaN
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                  NaN                  NaN                NaN                NaN              NaN              NaN              NaN

                                                                  balance_cp_mode  balance_auto_mean  balance_auto_mode  balance_ht_mean  balance_ht_mode  dividas_cl_mean  dividas_cl_mode  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981              0.0                0.0                0.0              0.0              0.0        2565.7936              0.0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981              0.0                0.0                0.0              0.0              0.0        2565.7936              0.0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297              0.0                0.0                0.0              0.0              0.0       26448.0320          26637.9
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              NaN                NaN                NaN              NaN              NaN              NaN              NaN
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              NaN                NaN                NaN              NaN              NaN              NaN              NaN

                                                                  dividas_cp_mean  dividas_cp_mode  dividas_auto_mean  dividas_auto_mode  dividas_ht_mean  dividas_ht_mode  ks_score_tier  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981        1150.5924          1729.30         13479.8216                0.0              0.0              0.0            2.0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981        1150.5924          1729.30         13479.8216                0.0              0.0              0.0            2.0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297        7552.1172          6746.45             0.0000                0.0              0.0              0.0            1.0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              NaN              NaN                NaN                NaN              NaN              NaN            NaN
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              NaN              NaN                NaN                NaN              NaN              NaN            NaN

                                                                  ALLBD_N_Dossiers__N  ALLBD_N_CL__N  ALLBD_N_CP__N  ALLBD_A_CL__N  ALLBD_A_CP__N  ALLBD_MTFINO_CL__N  ALLBD_MTFINO_CP__N  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                 10.0            5.0            5.0            1.0            2.0            29720.95             3381.52
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                 10.0            5.0            5.0            1.0            2.0            29720.95             3381.52
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297                 10.0            5.0            5.0            1.0            0.0            20000.00                0.00
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                  NaN            NaN            NaN            NaN            NaN                 NaN                 NaN
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                  NaN            NaN            NaN            NaN            NaN                 NaN                 NaN

                                                                  ALLBD_MTFIN_CL__N  ALLBD_MTFIN_CP__N  ALLBD_IDADE_MEAN__N  ALLBD_SUM_NUMFIN_CP__N  ALLBD_mean_active_resso__N  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981           29720.95               29.5               -438.9                    36.0                      1142.0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981           29720.95               29.5               -438.9                    36.0                      1142.0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297           20000.00                0.0               1166.9                     0.0                       850.0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                NaN                NaN                  NaN                     NaN                         NaN
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                NaN                NaN                  NaN                     NaN                         NaN

                                                                  ALLBD_max_active_resso__N  ALLBD_mean_duration_CL__N  ALLBD_mean_lifecycle_CL__N  ALLBD_N_events__N  sdem_age  active_credit_ratio  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                     1142.0                      120.0                    0.033333               10.0      33.0             0.272727
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                     1142.0                      120.0                    0.033333               10.0      33.0             0.272727
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297                      850.0                      120.0                    0.675000               10.0      52.0             0.090909
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                        NaN                        NaN                         NaN                NaN       NaN                  NaN
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                        NaN                        NaN                         NaN                NaN       NaN                  NaN

                                                                  debt_income_ratio  credit_progress  credit_remaining_ratio  kp_sqe_freq  POLE_P  POLE_nan  PAGAMENTO_OTHER  PAGAMENTO_P  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981          26.002581         0.999966                0.999966     0.032015       1         0                0            1
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981          26.002581         0.999966                0.999966     0.032015       1         0                0            1
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297          23.501763         0.999950                0.999950     0.032678       1         0                0            1
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                NaN              NaN                     NaN     0.592193       1         0                0            1
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                NaN              NaN                     NaN     0.592193       1         0                0            1

                                                                  PAGAMENTO_nan  is_risky_True  is_risky_nan  PRODALP_EP  PRODALP_EPF  PRODALP_EXT  PRODALP_nan  NATIO_P  NATIO_nan  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981              0              1             0           1            0            0            0        1          0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981              0              1             0           1            0            0            0        1          0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297              0              0             0           1            0            0            0        1          0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              0              0             1           1            0            0            0        1          0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              0              0             1           1            0            0            0        1          0

                                                                  MODCONTACTO_OTHER  MODCONTACTO_W  MODCONTACTO_nan  sdem_SITFAM_D  sdem_SITFAM_F  sdem_SITFAM_P  sdem_SITFAM_S  sdem_SITFAM_U  \
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                  0              1                0              0              0              0              1              0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981                  0              1                0              0              0              0              1              0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297                  0              0                0              0              0              0              0              0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                  1              0                0              0              0              0              0              0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a                  1              0                0              0              0              0              0              0

                                                                  sdem_SITFAM_V  sdem_SITFAM_X  sdem_SITFAM_nan  sdem_HABITAT_F  sdem_HABITAT_L  sdem_HABITAT_OTHER  sdem_HABITAT_P  sdem_HABITAT_nan
CONTRIB
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981              0              0                0               1               0                   0               0                 0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981              0              0                0               1               0                   0               0                 0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297              0              0                0               0               0                   0               1                 0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              0              0                1               0               0                   0               0                 1
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a              0              0                1               0               0                   0               0                 1

In [163]:
# matriz de correlação absoluta
corr_matrix = X.corr().abs()

# parte superior da matriz
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))

# colunas com correlação > 0.9
high_corr_cols = [col for col in upper.columns if any(upper[col] > 0.9)]

print("Número de colunas muito correlacionadas:", len(high_corr_cols))
print(high_corr_cols)

Número de colunas muito correlacionadas: 28
['count_cl_mode', 'count_cp_mode', 'count_auto_mode', 'count_ht_mode', 'count_conexo_mode', 'count_other_mode', 'montabatv_cl_mode', 'montabatv_cp_mode', 'montabatv_auto_mode', 'montabatv_ht_mode', 'balance_cl_mean', 'balance_cl_mode', 'balance_cp_mean', 'balance_cp_mode', 'balance_auto_mean', 'balance_auto_mode', 'balance_ht_mean', 'balance_ht_mode', 'dividas_cl_mode', 'dividas_cp_mode', 'dividas_ht_mode', 'ALLBD_N_CL__N', 'ALLBD_MTFIN_CL__N', 'ALLBD_max_active_resso__N', 'ALLBD_N_events__N', 'credit_remaining_ratio', 'is_risky_nan', 'sdem_HABITAT_nan']

In [ ]:
X = X.drop(columns=high_corr_cols)
X

,sol_count,san_count,enc_count,rbt_count,TIME_MONTHS,DURDEG,RANGPRO_max,RANGCLI_max,delay_mean,delay_max,MENSALIDADE,CRD_min,MTFINO,RESSO_mean,RISKA_mean,NBENF_mean,RN_mean,SREC,AGFIN,CSP,PTT,count_cl_mean,count_cp_mean,count_auto_mean,count_ht_mean,count_conexo_mean,count_other_mean,montvenc_cl_mean,montvenc_cl_mode,montvenc_cp_mean,montvenc_cp_mode,montvenc_auto_mean,montvenc_auto_mode,montvenc_ht_mean,montvenc_ht_mode,montabatv_cl_mean,montabatv_cp_mean,montabatv_auto_mean,montabatv_ht_mean,dividas_cl_mean,dividas_cp_mean,dividas_auto_mean,dividas_auto_mode,dividas_ht_mean,ks_score_tier,ALLBD_N_Dossiers__N,ALLBD_N_CP__N,ALLBD_A_CL__N,ALLBD_A_CP__N,ALLBD_MTFINO_CL__N,ALLBD_MTFINO_CP__N,ALLBD_MTFIN_CP__N,ALLBD_IDADE_MEAN__N,ALLBD_SUM_NUMFIN_CP__N,ALLBD_mean_active_resso__N,ALLBD_mean_duration_CL__N,ALLBD_mean_lifecycle_CL__N,sdem_age,active_credit_ratio,debt_income_ratio,credit_progress,kp_sqe_freq,POLE_P,POLE_nan,PAGAMENTO_OTHER,PAGAMENTO_P,PAGAMENTO_nan,is_risky_True,PRODALP_EP,PRODALP_EPF,PRODALP_EXT,PRODALP_nan,NATIO_P,NATIO_nan,MODCONTACTO_OTHER,MODCONTACTO_W,MODCONTACTO_nan,sdem_SITFAM_D,sdem_SITFAM_F,sdem_SITFAM_P,sdem_SITFAM_S,sdem_SITFAM_U,sdem_SITFAM_V,sdem_SITFAM_X,sdem_SITFAM_nan,sdem_HABITAT_F,sdem_HABITAT_L,sdem_HABITAT_OTHER,sdem_HABITAT_P
CONTRIB,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,0,1,3,0,3,84,3,19,1,1,158.359889,0.000,8000.00,1395.993500,0.0,0.0,0.0,0.000000,118.0,74.0,8600,0.36,3.8,1.12,0.0,0.0,1.08,0.000,0.0,0.000,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2565.7936,1150.5924,13479.8216,0.00,0.0,2.0,10.0,5.0,1.0,2.0,29720.95,3381.52,29.5,-438.900000,36.0,1142.0,120.0,0.033333,33.0,0.272727,26.002581,0.999966,0.032015,1,0,0,1,0,1,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0
00008246f87bcc3c17b90629bb183fe2e58795176310f017217d7749af7ee981,0,1,8,0,14,120,13,19,1,1,280.401466,0.000,16000.00,1513.466000,0.0,0.0,0.0,0.000000,118.0,80.0,8600,0.36,3.8,1.12,0.0,0.0,1.08,0.000,0.0,0.000,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2565.7936,1150.5924,13479.8216,0.00,0.0,2.0,10.0,5.0,1.0,2.0,29720.95,3381.52,29.5,-438.900000,36.0,1142.0,120.0,0.033333,33.0,0.272727,26.002581,0.999966,0.032015,1,0,0,1,0,1,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0
0000ab2116257783438c70ff85a3e98f2d4194ebe534349a33373dfcb3a3a297,0,0,23,0,92,120,91,91,0,1,347.447280,8115.247,20000.00,1113.258000,0.0,1.0,0.0,15.106391,120.0,80.0,2845,4.32,5.4,0.0,0.0,0.0,1.08,0.000,0.0,0.000,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,26448.0320,7552.1172,0.0000,0.00,0.0,1.0,10.0,5.0,1.0,0.0,20000.00,0.00,0.0,1166.900000,0.0,850.0,120.0,0.675000,52.0,0.090909,23.501763,0.999950,0.032678,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a,1,0,0,0,270,60,21,21,0,0,184.214593,0.000,5985.57,678.483000,0.0,2.0,1.0,0.000000,117.0,60.0,2745,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.592193,1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
0000c74654405ec1da4dbdcd00b86e397954043965d98e542d19fa4808c6b65a,1,0,0,0,270,60,21,21,0,0,424.699203,0.000,13467.54,678.483000,0.0,2.0,1.0,0.000000,117.0,60.0,2745,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.592193,1,0,0,1,0,0,1,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
fffc991d73df732084dab58938d520b8a5d8712474fa53902c42190d5b1e0f9b,1,0,0,0,35,34,34,34,0,0,57.095138,0.000,1500.00,896.196000,0.0,1.0,0.0,0.000000,118.0,80.0,4400,0.36,2.0,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,106.0964,1.1988,0.0000,0.00,0.0,NaN,4.0,3.0,0.0,1.0,1500.00,1495.00,0.0,-307.000000,4.0,600.0,0.0,0.000000,33.0,0.200000,2.495840,0.999334,0.592193,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1
fffd54b6dbb4cc001fb8ab52a905cff9bdbf14b747be9a9adcf1007f61b9a9c4,0,0,23,0,53,60,53,53,0,1,416.654611,2563.528,15000.00,1623.880000,0.0,0.0,0.0,0.000000,120.0,80.0,9560,1.0,1.0,1.0,0.0,0.0,0.0,0.000,0.0,0.000,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5612.6424,1758.3716,20498.1268,21693.13,0.0,NaN,3.0,1.0,1.0,0.0,15000.00,0.00,0.0,-1356.666667,0.0,1222.0,60.0,0.716667,33.0,0.250000,12.264922,0.999933,0.592193,1,0,0,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0
fffe8c5cbb44ad3ec6154ef5a5208ecd76594a88377f00c5ce4e07c92bfe1f3b,0,1,2,0,24,84,23,34,1,1,267.471639,0.000,12000.00,955.766667,0.333333,0.0,0.0,233.510333,117.0,80.0,2845,2.12,1.2,0.0,0.0,0.0,0.0,0.000,0.0,0.000,0.00,0.000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,16939.2728,3668.6836,0.0000,0.00,0.0,NaN,17.0,4.0,1.0,0.0,29897.00,0.00,0.0,-1464.823529,0.0,792.0,156.0,0.064103,33.0,0.055556,37.701135,0.999967,0.592193,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0
ffff943c736f98d4840f65328ba372a29689312dd781b437624e6112d3d6803b,0,0,1,0,3,24,3,6,0,0,135.336545,2572.760,2500.00,924.580000,1.0,0.0,1.0,0.000000,119.0,60.0,2825,0.9,4.1,1.0,0.0,0.0,0.0,852.871,0.0,509.255,748.84,1993.652,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2131.6990,3809.9870,18609.6080,18581.09,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.592193,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0
ffffe82f7c91df4a087341fe89db094be2a89294f2178572b937a270b0c9f669,0,1,0,0,35,84,32,87,0,0,415.242666,0.000,20000.00,2234.521000,0.0,1.0,0.0,0.000000,117.0,60.0,2730,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,1.0,0.0,0.0,40733.44,0.00,0.0,2924.800000,0.0,0.0,0.0,0.000000,41.0,0.000000,40733.440000,0.999975,0.592193,1,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0

ANOVA

In [196]:
X = X.copy().astype('float64')
X = X.fillna(0)

y= y.map({True: 1, False: 0}).fillna(0)

In [199]:
from sklearn.feature_selection import SelectKBest, f_classif

# criar o seletor ANOVA
selector = SelectKBest(score_func=f_classif, k=50)

# ajustar o seletor aos dados
selector.fit(X, y)

# guardar apenas os nomes das colunas escolhidas
selected_features = X.columns[selector.get_support()]

# criar uma tabela com o score de cada variável
anova_scores = pd.DataFrame({
    'feature': X.columns,
    'score': selector.scores_
})

# ordenar do maior score para o menor
anova_scores = anova_scores.sort_values('score', ascending=False)

# ver as 50 melhores
print(anova_scores.head(50))

# reduzir o X só para as 50 melhores variáveis
X_anova = X[selected_features].copy()

print("Shape original:", X.shape)
print("Shape depois do ANOVA:", X_anova.shape)

                       feature          score
1                    san_count  171681.271024
11                     CRD_min   62450.123937
0                    sol_count   59691.685849
2                    enc_count   57690.471699
8                   delay_mean   18781.489325
55   ALLBD_mean_duration_CL__N   17941.700601
47               ALLBD_A_CL__N   11828.736240
4                  TIME_MONTHS   11354.469044
58         active_credit_ratio    8587.152482
59           debt_income_ratio    7578.351631
5                       DURDEG    4996.726822
76             MODCONTACTO_nan    4938.650459
56  ALLBD_mean_lifecycle_CL__N    4563.545347
65                 PAGAMENTO_P    2962.619906
23             count_auto_mean    2554.478164
42           dividas_auto_mode    2213.888964
21               count_cl_mean    2140.039618
12                      MTFINO    1990.440517
74           MODCONTACTO_OTHER    1985.644689
6                  RANGPRO_max    1936.475167
41           dividas_auto_mean    1905.980127
9                    delay_max    1743.689630
61                 kp_sqe_freq    1380.582134
67               is_risky_True    1330.929991
44               ks_score_tier    1118.695533
45         ALLBD_N_Dossiers__N     943.378096
84             sdem_SITFAM_nan     900.984469
54  ALLBD_mean_active_resso__N     841.001537
10                 MENSALIDADE     840.259640
14                  RISKA_mean     835.499985
57                    sdem_age     762.242481
75               MODCONTACTO_W     762.060413
52         ALLBD_IDADE_MEAN__N     737.446660
49          ALLBD_MTFINO_CL__N     365.397670
40             dividas_cp_mean     360.322940
17                        SREC     349.053537
83               sdem_SITFAM_X     334.984314
46               ALLBD_N_CP__N     308.531002
18                       AGFIN     215.458041
7                  RANGCLI_max     144.538312
22               count_cp_mean     138.324485
39             dividas_cl_mean     123.472724
80               sdem_SITFAM_S      99.162615
77               sdem_SITFAM_D      90.975742
29            montvenc_cp_mean      79.388266
70                 PRODALP_EXT      76.036341
20                         PTT      66.653343
68                  PRODALP_EP      53.286487
15                  NBENF_mean      50.087136
82               sdem_SITFAM_V      49.200824
Shape original: (185600, 89)
Shape depois do ANOVA: (185600, 50)

c:\Users\alano\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:111: UserWarning: Features [ 3 63 66 71 73] are constant.
  warnings.warn("Features %s are constant." % constant_features_idx, UserWarning)
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\feature_selection\_univariate_selection.py:112: RuntimeWarning: invalid value encountered in divide
  f = msb / msw

In [201]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import RobustScaler, StandardScaler

scaler = RobustScaler()
X_anova_scaled = pd.DataFrame(
    scaler.fit_transform(X_anova),
    columns=X_anova.columns,
    index=X_anova.index
)


# modelo base usado para avaliar as variáveis
model = LogisticRegression(max_iter=2000, random_state=42)

# criar o seletor RFE para escolher 25 variáveis
selector_rfe = RFE(estimator=model, n_features_to_select=25)

# ajustar o RFE aos dados
selector_rfe.fit(X_anova, y)

# nomes das variáveis escolhidas
rfe_selected_features = X_anova.columns[selector_rfe.support_]

# ranking de todas as variáveis
rfe_ranking = pd.DataFrame({
    'feature': X_anova.columns,
    'ranking': selector_rfe.ranking_,
    'selected': selector_rfe.support_
}).sort_values(['ranking', 'feature'])

# novo dataset só com as 25 escolhidas
X_rfe = X_anova[rfe_selected_features].copy()

print(rfe_ranking)
print("\nVariáveis escolhidas:")
print(rfe_selected_features.tolist())
print("\nShape antes:", X_anova.shape)
print("Shape depois:", X_rfe.shape)

c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\alano\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

                       feature  ranking  selected
28               ALLBD_A_CL__N        1      True
27               ALLBD_N_CP__N        1      True
26         ALLBD_N_Dossiers__N        1      True
33  ALLBD_mean_lifecycle_CL__N        1      True
10                     CRD_min        1      True
42           MODCONTACTO_OTHER        1      True
44             MODCONTACTO_nan        1      True
38                 PAGAMENTO_P        1      True
40                  PRODALP_EP        1      True
5                  RANGPRO_max        1      True
12                  RISKA_mean        1      True
3                  TIME_MONTHS        1      True
35         active_credit_ratio        1      True
17               count_cl_mean        1      True
18               count_cp_mean        1      True
7                   delay_mean        1      True
2                    enc_count        1      True
39               is_risky_True        1      True
37                 kp_sqe_freq        1      True
25               ks_score_tier        1      True
1                    san_count        1      True
45               sdem_SITFAM_D        1      True
46               sdem_SITFAM_S        1      True
48               sdem_SITFAM_X        1      True
0                    sol_count        1      True
19             count_auto_mean        2     False
41                 PRODALP_EXT        3     False
47               sdem_SITFAM_V        4     False
32   ALLBD_mean_duration_CL__N        5     False
4                       DURDEG        6     False
13                  NBENF_mean        7     False
34                    sdem_age        8     False
43               MODCONTACTO_W        9     False
6                  RANGCLI_max       10     False
20            montvenc_cp_mean       11     False
15                       AGFIN       12     False
14                        SREC       13     False
9                  MENSALIDADE       14     False
31  ALLBD_mean_active_resso__N       15     False
16                         PTT       16     False
23           dividas_auto_mean       17     False
30         ALLBD_IDADE_MEAN__N       18     False
11                      MTFINO       19     False
22             dividas_cp_mean       20     False
8                    delay_max       21     False
29          ALLBD_MTFINO_CL__N       22     False
36           debt_income_ratio       23     False
21             dividas_cl_mean       24     False
49             sdem_SITFAM_nan       25     False
24           dividas_auto_mode       26     False

Variáveis escolhidas:
['sol_count', 'san_count', 'enc_count', 'TIME_MONTHS', 'RANGPRO_max', 'delay_mean', 'CRD_min', 'RISKA_mean', 'count_cl_mean', 'count_cp_mean', 'ks_score_tier', 'ALLBD_N_Dossiers__N', 'ALLBD_N_CP__N', 'ALLBD_A_CL__N', 'ALLBD_mean_lifecycle_CL__N', 'active_credit_ratio', 'kp_sqe_freq', 'PAGAMENTO_P', 'is_risky_True', 'PRODALP_EP', 'MODCONTACTO_OTHER', 'MODCONTACTO_nan', 'sdem_SITFAM_D', 'sdem_SITFAM_S', 'sdem_SITFAM_X']

Shape antes: (185600, 50)
Shape depois: (185600, 25)